class AppStrings {
  static const Map<String, Map<String, String>> _localizedValues = {
    'ar': {
      'settings': 'الإعدادات',
      'profile': 'الملف الشخصي',
      'name': 'الاسم',
      'change_photo': 'تغيير الصورة',
      'theme': 'المظهر',
      'display_mode': 'وضع العرض',
      'light': 'فاتح',
      'dark': 'داكن',
      'system': 'تلقائي',
      'notifications': 'الإشعارات',
      'enable_notifications': 'تفعيل الإشعارات',
      'notifications_desc': 'استقبال إشعارات الدروس والاختبارات',
      'downloads': 'التحميل',
      'auto_download': 'التحميل التلقائي',
      'auto_download_desc': 'تحميل الدروس تلقائياً عند الاتصال بالواي فاي',
      'wifi_only': 'التحميل عبر واي فاي فقط',
      'wifi_only_desc': 'توفير استهلاك البيانات عبر شبكة الجوال',
      'video_quality': 'جودة الفيديو',
      'clear_downloads': 'مسح التنزيلات',
      'clear_downloads_desc': 'حذف جميع الدروس المحملة لتوفير المساحة',
      'about': 'حول الكورس ',
      'version': 'الإصدار',
      'privacy_policy': 'سياسة الخصوصية',
      'terms_conditions': 'شروط الاستخدام',
      'language': 'اللغة',
      'app_language': 'لغة التطبيق',
      'educational_info': 'معلومات تعليمية',
      'professional_info': 'معلومات مهنية',
      'education_level': 'المستوى التعليمي',
      'grade': 'الصف/السنة',
      'specialization': 'التخصص',
      'bio': 'نبذة تعريفية',
      'country': 'البلد',
      'logout': 'تسجيل الخروج',
      'logout_confirm_title': 'تسجيل الخروج',
      'logout_confirm_desc': 'هل أنت متأكد من تسجيل الخروج؟',
      'cancel': 'إلغاء',
      'save': 'حفظ',
      'edit_name': 'تعديل الاسم',
      'enter_full_name': 'أدخل الاسم الكامل',
      'choose_photo': 'اختيار الصورة',
      'camera': 'الكاميرا',
      'gallery': 'معرض الصور',
      'video_quality_high': 'عالية',
      'video_quality_medium': 'متوسطة',
      'video_quality_low': 'منخفضة',
      'clear_downloads_confirm_title': 'مسح التنزيلات',
      'clear_downloads_confirm_desc': 'هل أنت متأكد من مسح جميع الدروس المحملة؟',
      'clear': 'مسح',
      'clearing': 'جاري مسح التنزيلات...',
      'clear_success': 'تم مسح جميع التنزيلات بنجاح',
      'error_loading': 'خطأ في تحميل البيانات',
      'changes_saved': 'تم حفظ التغييرات',
      'error_saving': 'خطأ في حفظ التغييرات',
      'error_image_pick': 'خطأ في اختيار الصورة',
      'error_image_upload': 'خطأ في رفع الصورة',
      'error_logout': 'خطأ في تسجيل الخروج',
      'contact_support': 'تواصل مع الدعم',
      'support_desc': 'الدعم الفني والمساعدة',
      'delete_account': 'حذف الحساب',
      'delete_account_desc': 'حذف حسابك وجميع بياناتك نهائياً',
      'delete_confirm_title': 'حذف الحساب',
      'delete_confirm_desc': 'هل أنت متأكد من رغبتك في حذف حسابك؟ هذا الإجراء لا يمكن التراجع عنه.',
      'delete': 'حذف',
      'support_dialog_title': 'الدعم الفني',
      'support_dialog_desc': 'يمكنك التواصل معنا عبر الوسائل التالية:',
      'email_us': 'راسلنا عبر البريد الإلكتروني',
      'whatsapp_us': 'تواصل معنا عبر واتساب',
      'home': 'الرئيسية',
      'explore': 'تصفح',
      'my_courses': 'دوراتي',
      'welcome': 'أهلاً بك يا ضيف',
      'guest': 'ضيف',
      'searching': 'ابحث عن درسك التالي...',
      'categories': 'التصنيفات',
      'all': 'الكل',
      'top_teachers': 'أفضل المعلمين',
      'continue_watching': 'متابعة المشاهدة',
      'explore_more': 'تصفح المزيد',
      'search_courses': 'البحث عن الدورات',
      'search_hint': 'ابحث باسم الدورة أو المعلم...',
      'filter': 'تصفية',
      'filter_by_category': 'تصفية حسب التصنيف',
      'my_downloads': 'تنزيلاتي',
      'edit_profile': 'تعديل الملف الشخصي',
      'statistics': 'الإحصائيات',
      'joined': 'انضم في',
      'completed_courses': 'الدورات المكتملة',
      'hours_spent': 'ساعات الدراسة',
      'no_courses_found': 'لم يتم العثور على دورات',
      'try_different_search': 'حاول البحث بكلمات مختلفة',
      'featured_courses': 'دورات مميزة',
      'no_featured_courses_message': 'لم يتم العثور على أي دورات مميزة في الوقت الحالي.',
      'welcome_with_name': 'أهلاً بك يا',

      'ready_to_learn': 'جاهز للتعلم؟',
      'search_course_hint': 'ابحث عن دورة...',
      'continue_learning': 'تابع التعلم',
      'completed': 'اكتمل',
      'featured_course_badge': 'دورة مميزة',
      'most_popular': 'الأكثر طلباً',
      'teacher': 'مدرس',
      'explore_courses': 'استكشف الدورات',
      'no_courses_in_category': 'لا توجد دورات في هذا القسم',
      'no_categories_found': 'لم يتم العثور على تصنيفات',
      'loading': 'جاري التحميل...',
      'current_courses': 'دوراتي الحالية',
      'completed_status': 'مكتملة',
      'enrolled': 'مسجل',
      'no_current_courses': 'لا توجد دورات حالية',
      'no_completed_courses': 'لا توجد دورات مكتملة بعد',
      'unenroll_confirm': 'هل أنت متأكد من إلغاء التسجيل؟',
      'unenroll_success': 'تم إزالة الدورة من قائمتك',
      'unenroll_error': 'حدث خطأ أثناء إلغاء التسجيل',
      'course_removed': 'تم إزالة الدورة بنجاح',
      'no_current_courses_desc': 'ابدأ بتصفح الدورات وسجل في اهتماماتك!',
      'no_completed_courses_desc': 'بمجرد إنهاء الدورة، ستظهر هنا في قائمة المكتملة.',
      'current': 'الحالية',
      'admin_dashboard': 'لوحة تحكم المشرف',
      'teacher_dashboard': 'لوحة تحكم الأستاذ',
      'account_upgrades': 'ترقيات الحساب',
      'certificates': 'شهادات',
      'learning_hours': 'ساعة تعلم',
      'orders': 'طلباتي',
      'dashboard': 'لوحة التحكم',
      'performance_summary': 'ملخص الأداء',
      'active_students': 'الطلاب النشطون',
      'total_revenue': 'إجمالي الدخل',
      'courses_count': 'عدد الكورسات',
      'user': 'المستخدم',
      'completed_courses_count_label': 'دورة مكتملة',
      'no_orders_yet': 'لا توجد طلبات سابقة',
      'no_orders_desc': 'لم تقم بشراء أي دورات بعد. جميع فواتيرك ستظهر هنا.',
      'study_continue': 'استمر في الدراسة!',
      'courses_not_completed_desc': 'لم تكمل أي دورة بالكامل حتى الآن. استمر في الدراسة!',
      'enrolled_courses_desc': 'ابدأ رحلتك التعليمية اليوم واستكشف دوراتنا المتاحة.',
      'no_courses_yet': 'لم تشتر أي دورة بعد',
      'course_description': 'وصف الدورة',
      'curriculum_tab': 'المنهاج',
      'reviews_tab': 'التقييمات',
      'buy_now': 'اشترِ الآن',
      'enrolled_already': 'أنت مسجل في هذه الدورة',
      'pending_request': 'طلبك قيد المراجعة',
      'download_course': 'تنزيل الدورة',
      'get_certificate': 'الحصول على الشهادة',
      'lesson': 'درس',
      'lessons': 'دروس',
      'exam': 'اختبار',
      'free': 'مجاني',
      'certificate_ready': 'الشهادة جاهزة!',
      'premium_course': 'دورة مميزة',
      'no_instructor_profile': 'لا يوجد ملف شخصي لهذا المدرب حالياً',
      'instructor_title': 'الأستاذ',
      'reviews_count_label': 'تقييم',
      'reviews_label': 'تقييم',
      'progress_label': 'التقدم',
      'offline_badge_label': 'محمّل على الجهاز',
      'unenroll_button_label': 'حذف من قائمتي',
      'course_unavailable_label': 'هذه الدورة غير متاحة حالياً',
      'no_active_courses': 'لا توجد دورات حالية',
      'start_learning_message': 'ابدأ بإضافة دورات من الصفحة الرئيسية',
      'keep_learning_message': 'استمر في التعلم لإكمال دوراتك!',
      'confirm_delete_title': 'تأكيد الحذف',
      'confirm_delete_message': 'هل تريد إزالة هذه الدورة من قائمتك؟',
      'error_label': 'خطأ',
      'lessons_count_label': 'درس',
      'students_count_label': 'طالب',
      'duration_label': 'ساعة',
      'hours_short': 'ساعة',
      'duration': 'المدة',
      'accredited_by': 'معتمد من قبل',
      'no_reviews_yet': 'لا توجد تقييمات بعد',
      'reviews': 'تقييمات',
      'add_review': 'أضف تقييمك',
      'your_comment_here': 'اكتب تعليقك هنا...',
      'publish': 'نشر',
      'adding_review': 'جاري إضافة التقييم...',
      'review_added_success': 'تم إضافة تقييمك بنجاح',
      'no_lessons_yet': 'لا توجد دروس حالياً',
      'course_content_working': 'يتم العمل على إضافة محتوى لهذه الدورة قريباً.',
      'other_lessons': 'دروس أخرى',
      'course_content': 'محتوى الدورة',
      'must_complete_previous': 'يجب إكمال الدرس السابق أولاً',
      'description_tab': 'الوصف',
      'attachments_tab': 'المرفقات',
      'interactive_tab': 'تفاعل',
      'exams_tab': 'اختبارات',
      'notes_tab': 'الملاحظات',
      'questions_tab': 'الأسئلة',
      'lesson_prefix': 'الدرس',
      'starting_download': 'جاري تجهيز الملف...',
      'download_success_encrypted': 'تم تجهيز الملف بنجاح',
      'download_error': 'خطأ في التحميل',
      'delete_note': 'حذف الملاحظة',
      'delete_note_confirm': 'هل أنت متأكد من رغبتك في حذف هذه الملاحظة؟',
      'note_deleted_success': 'تم حذف الملاحظة بنجاح',
      'edit_note': 'تعديل الملاحظة',
      'no_video_available': 'لا يوجد فيديو لهذا الدرس',
      'no_interactive_content': 'لا يوجد محتوى تفاعلي مخصص لهذا الدرس',
      'recent_exam_attempts': 'أحدث محاولات الطلاب',
      'no_recent_attempts': 'لا توجد محاولات حديثة',
      'must_subscribe': 'يجب الاشتراك في المادة لمشاهدة هذا الدرس',
      'no_exam_at_all': 'لا يوجد اختبار لهذا الدرس. الانتقال للدرس التالي...',
      'must_take_exam': 'يجب اجتياز اختبار هذا الدرس أولاً',
      'start_exam': 'بدء الاختبار',
      'ai_assistant': 'المساعد الذكي',
      'ai_assistant_coming_soon': 'ستتاح ميزة الذكاء الاصطناعي في تحديث قادم',
      'ai_features_notice':
          'نحن نعمل على دمج تقنيات الذكاء الاصطناعي لتعزيز تجربتك التعليمية.',
      'view_details': 'عرض التفاصيل',
      'order_report': 'تقرير الطلب',
      'details': 'التفاصيل',
      'transaction_id': 'رقم العملية',
      'payment_method': 'طريقة الدفع',
      'phone_number': 'رقم الهاتف',
      'order_date': 'Order Date',
      'total_amount': 'المبلغ الإجمالي',
      'status': 'الحالة',
      'order_number': 'رقم الطلب',
      'app_updates': 'تحديثات التطبيق',
      'manage_app_updates': 'إدارة تحديثات النظام',
      'version_name': 'رقم الإصدار',
      'download_url': 'رابط التحميل',
      'release_notes': 'ملاحظات الإصدار',
      'is_mandatory_label': 'تحديث إجباري',
      'add_update': 'إضافة تحديث جديد',
      'update_success': 'تم إضافة التحديث بنجاح',
      'mandatory': 'إجباري',
      'optional': 'اختياري',
      'show_all': 'عرض الكل',
      'discount_percentage': 'نسبة الخصم (%)',
      'enter_discount': 'أدخل نسبة الخصم',
      'discount_range_error': 'يجب أن تكون النسبة بين 0 و 100',
      'manage_my_courses': 'إدارة دوراتي',
      'manage_course': 'إدارة الدورة',
      'manage_courses': 'إدارة الدورات',
      'total_courses_count': 'إجمالي {count} دورة تعليمية',
      'general_specialization': 'تخصص عام',
      'published': 'منشور',
      'draft': 'مسودة',
      'unspecified_teacher': 'مدرس غير محدد',
      'exams': 'الاختبارات',
      'edit': 'تعديل',
      'no_courses_current': 'لا توجد دورات حالياً',
      'start_adding_first_course': 'ابدأ بإضافة أول دورة تعليمية للمنصة',
      'delete_course_title': 'حذف الدورة',
      'delete_course_confirm': 'هل أنت متأكد من حذف هذه الدورة؟ سيتم حذف جميع الدروس المرتبطة بها.',
      'close': 'إغلاق',
      'subscribers': 'المشتركين',
      'completers': 'المكملين',
      'average_progress_label': 'متوسط التقدم',
      'completion_rate_label': 'معدل الإكمال',
      'course_outcomes': 'نتائج الدورة',
      'target_audience': 'الفئة المستهدفة',
      'own_this_course': 'امتلك الدورة بـ',
      'register_and_get': 'سجل بهذه الدورة واحصل على',
      'unending_views': 'مشاهدة غير محدودة للدورة',
      'contact_coach': 'التواصل مع المدرب',
      'completion_certificate': 'شهادة إتمام الدورة',
      'or': 'أو',
      'subscribe_now_prefix': 'اشترك الآن - ',
      'all_levels': 'جميع المستويات',
      'beginner': 'مبتدئ',
      'intermediate': 'متوسط',
      'expert': 'خبير',
      'decision_making': 'اتخاذ القرار',
      'goal_achievement': 'تحقيق اهداف',
      'self_development': 'تطوير الذات',
      'order_priorities': 'تنظيم اولويات',
      'body_language': 'لغة الجسد',
      'edit_course': 'تعديل الدورة',
      'create_new_course': 'إنشاء دورة جديدة',
      'select_teacher': 'اختر المدرس المسئول',
      'search_teacher': 'بحث عن مدرس...',
      'pricing_time_data': 'بيانات التسعير والوقت',
      'free_course': 'دورة مجانية',
      'free_course_desc': 'سيتمكن جميع الطلاب من الوصول إليها بدون دفع',
      'price': 'السعر',
      'price_hint': '0 للمجاني',
      'currency': 'العملة',
      'instructor_and_visibility': 'المدرس والظهور',
      'unspecified': 'غير محدد',
      'is_published_label': 'الحالة: منشور',
      'subject_label': 'المادة',
      'subject_hint': 'مثال: فيزياء',
      'error_enter_subject': 'الرجاء إدخال اسم المادة',
      'level_label': 'المستوى',
      'tags_optional_label': 'الوسوم (اختياري):',
      'basic_info_label': 'المعلومات الأساسية',
      'course_title_label': 'عنوان الدورة',
      'course_title_hint': 'مثال: دورة الرياضيات المتقدمة',
      'error_enter_title': 'الرجاء إدخال عنوان الدورة',
      'course_description_hint': 'وصف مفصل عن محتوى الدورة',
      'error_enter_description': 'الرجاء إدخال وصف الدورة',
      'course_category_label': 'تصنيف الدورة',
      'select_category_label': 'اختر التصنيف',
      'course': 'دورة',
      'welcome_to_doraty': 'أهلاً بك في منصة دوراتي',
      'select_account_type': 'الرجاء اختيار نوع حسابك للمتابعة',
      'join_as_student': 'انضم كطالب',
      'student_desc': 'تصفح الدورات وتعلم مهارات جديدة',
      'join_as_teacher': 'انضم كمدرس',
      'teacher_desc': 'انشر دوراتك وابدأ بالتدريس',
      'first_name_label': 'الاسم الأول',
      'last_name_label': 'الاسم الأخير',
      'username_label': 'اسم المستخدم',
      'email_label': 'البريد الإلكتروني',
      'password_label': 'كلمة المرور',
      'confirm_password_label': 'تأكيد كلمة المرور',
      'terms_accept_label': 'أنا موافق على الشروط والأحكام',
      'personal_info': 'المعلومات الشخصية',
      'educational_info_header': 'المعلومات التعليمية',
      'security_header': 'الأمان',
      'required_suffix': '(مطلوب)',
      'invalid_email': 'بريد غير صحيح',
      'pass_min_char': '6 أحرف على الأقل',
      'pass_dont_match': 'كلمات المرور لا تتطابق',
      'grade_level_label': 'المرحلة الدراسية',
      'university_specialization_label': 'التخصص الجامعي',
      'academic_year_label': 'السنة الدراسية',
      'required_field': 'مطلوب',
      'register_new_coach': 'تسجيل مدرب جديد',
      'participation_plans': 'خطط المشاركة',
      'participation_intent_label': 'أرغب في الاشتراك في المنصة في (مطلوب):',
      'phone_number_label': 'رقم الجوال',
      'country_label': 'البلد',
      'specialization_label': 'التخصص',
      'give_full_courses_label': 'إعطاء دورات كاملة',
      'teach_private_hours_label': 'تدريس ساعات خصوصية',
      'cv_label': 'السيرة الذاتية',
      'certificates_label': 'الشهادات العلمية',
      'short_bio_hint': 'نبذة قصيرة عنك',
      'success_submit_teacher': 'تم إرسال طلبك بنجاح! سنقوم بمراجعته والرد عليك قريباً',
      'select_sub_type_error': 'الرجاء اختيار نوع الاشتراك (دورات أو ساعات خصوصية)',
      'fail_get_user_id': 'فشل الحصول على معرف المستخدم',
      'no_file_selected': 'لم يتم اختيار ملف (الحد الأقصى 5MB)',
      'change': 'تغيير',
      'choose': 'اختيار',
      'submit_request': 'تقديم الطلب',
      'create_account': 'إنشاء الحساب',
      'school': 'مدرسة',
      'university': 'جامعة',
      'save_changes': 'حفظ التعديلات',
      'course_created_success': 'تم إنشاء الدورة بنجاح',
      'course_updated_success': 'تم تحديث الدورة بنجاح',
      'error_saving_data': 'خطأ في حفظ البيانات',
      'select_at_least_one_category': 'الرجاء اختيار تصنيف واحد على الأقل',
      'register_title': 'إنشاء حساب جديد',
      'register_subtitle': 'انضم إلينا وابدأ رحلتك التعليمية',
      'student_role': 'طالب',
      'teacher_role': 'مدرس',
      'register_action': 'إنشاء الحساب',
      'already_have_account': 'لديك حساب بالفعل؟',
      'login_now': 'سجل دخولك الآن',
      'or_via': 'أو عبر',
      'account_created_success': 'تم إنشاء الحساب بنجاح! مرحباً بك',
    },
    'en': {
      'settings': 'Settings',
      'profile': 'Profile',
      'name': 'Name',
      'change_photo': 'Change Photo',
      'theme': 'Appearance',
      'display_mode': 'Display Mode',
      'light': 'Light',
      'dark': 'Dark',
      'system': 'System',
      'notifications': 'Notifications',
      'enable_notifications': 'Enable Notifications',
      'notifications_desc': 'Receive notifications for lessons and exams',
      'downloads': 'Downloads',
      'auto_download': 'Auto Download',
      'auto_download_desc': 'Automatically download lessons when connected to Wi-Fi',
      'wifi_only': 'Wi-Fi Only',
      'wifi_only_desc': 'Save data by downloading only over Wi-Fi',
      'video_quality': 'Video Quality',
      'clear_downloads': 'Clear Downloads',
      'clear_downloads_desc': 'Delete all downloaded lessons to save space',
      'about': 'About',
      'version': 'Version',
      'privacy_policy': 'Privacy Policy',
      'terms_conditions': 'Terms of Service',
      'language': 'Language',
      'app_language': 'App Language',
      'educational_info': 'Educational Info',
      'professional_info': 'Professional Info',
      'education_level': 'Education Level',
      'grade': 'Grade/Year',
      'specialization': 'Specialization',
      'bio': 'Bio',
      'country': 'Country',
      'logout': 'Log Out',
      'logout_confirm_title': 'Log Out',
      'logout_confirm_desc': 'Are you sure you want to log out?',
      'cancel': 'Cancel',
      'save': 'Save',
      'edit_name': 'Edit Name',
      'enter_full_name': 'Enter full name',
      'choose_photo': 'Choose Photo',
      'camera': 'Camera',
      'gallery': 'Gallery',
      'video_quality_high': 'High',
      'video_quality_medium': 'Medium',
      'video_quality_low': 'Low',
      'clear_downloads_confirm_title': 'Clear Downloads',
      'clear_downloads_confirm_desc': 'Are you sure you want to clear all downloads?',
      'clear': 'Clear',
      'clearing': 'Clearing downloads...',
      'clear_success': 'All downloads cleared successfully',
      'error_loading': 'Error loading data',
      'changes_saved': 'Changes saved',
      'error_saving': 'Error saving changes',
      'error_image_pick': 'Error picking image',
      'error_image_upload': 'Error uploading image',
      'error_logout': 'Error logging out',
      'contact_support': 'Contact Support',
      'support_desc': 'Technical support and help',
      'delete_account': 'Delete Account',
      'delete_account_desc': 'Permanently delete your account and data',
      'delete_confirm_title': 'Delete Account',
      'delete_confirm_desc': 'Are you sure you want to delete your account? This action cannot be undone.',
      'delete': 'Delete',
      'support_dialog_title': 'Technical Support',
      'support_dialog_desc': 'You can contact us through:',
      'email_us': 'Email Us',
      'whatsapp_us': 'WhatsApp Us',
      'home': 'Home',
      'explore': 'Explore',
      'my_courses': 'My Courses',
      'welcome': 'Welcome, Guest',
      'guest': 'Guest',
      'searching': 'Search your next lesson...',
      'categories': 'Categories',
      'all': 'All',
      'top_teachers': 'Top Teachers',
      'continue_watching': 'Continue Watching',
      'explore_more': 'Explore More',
      'search_courses': 'Search Courses',
      'search_hint': 'Search by course or teacher...',
      'filter': 'Filter',
      'filter_by_category': 'Filter by Category',
      'my_downloads': 'My Downloads',
      'edit_profile': 'Edit Profile',
      'statistics': 'Statistics',
      'joined': 'Joined',
      'completed_courses': 'Completed Courses',
      'hours_spent': 'Study Hours',
      'no_courses_found': 'No courses found',
      'try_different_search': 'Try searching with different keywords',
      'featured_courses': 'Featured Courses',
      'no_featured_courses_message': 'No featured courses found at the moment.',
      'welcome_with_name': 'Welcome,',
      'lessons': 'lessons',
      'ready_to_learn': 'Ready to learn?',
      'search_course_hint': 'Search for a course...',
      'continue_learning': 'Continue Learning',
      'completed': 'Completed',
      'featured_course_badge': 'Featured',
      'most_popular': 'Most Popular',
      'teacher': 'Teacher',
      'explore_courses': 'Explore Courses',
      'no_courses_in_category': 'No courses in this category',
      'no_categories_found': 'No categories found',
      'loading': 'Loading...',
      'current_courses': 'Current Courses',
      'completed_status': 'Completed',
      'reviews': 'reviews',
      'enrolled': 'Enrolled',
      'no_current_courses': 'No current courses',
      'no_completed_courses': 'No completed courses yet',
      'unenroll_confirm': 'Are you sure you want to unenroll?',
      'unenroll_success': 'Course removed from your list',
      'unenroll_error': 'Error during unenrollment',
      'course_removed': 'Course removed successfully',
      'no_current_courses_desc': 'Start exploring courses and enroll in your interests!',
      'no_completed_courses_desc': 'Once you finish a course, it will appear here in the completed list.',
      'current': 'Current',
      'admin_dashboard': 'Admin Dashboard',
      'teacher_dashboard': 'Teacher Dashboard',
      'manage_course': 'Manage Course',
      'account_upgrades': 'Account Upgrades',
      'certificates': 'Certificates',
      'learning_hours': 'Learning Hours',
      'orders': 'My Orders',
      'dashboard': 'Dashboard',
      'performance_summary': 'Performance Summary',
      'active_students': 'Active Students',
      'total_revenue': 'Total Revenue',
      'courses_count': 'Courses Count',
      'user': 'User',
      'completed_courses_count_label': 'Completed Course(s)',
      'no_orders_yet': 'No previous orders',
      'no_orders_desc': 'You haven\'t purchased any courses yet. All your bills will appear here.',
      'study_continue': 'Keep studying!',
      'courses_not_completed_desc': 'You haven\'t completed any course fully yet. Keep studying!',
      'enrolled_courses_desc': 'Start your educational journey today and explore our available courses.',
      'no_courses_yet': 'You haven\'t purchased any course yet',
      'course_description': 'Course Description',
      'curriculum_tab': 'Curriculum',
      'reviews_tab': 'Reviews',
      'reviews_label': 'Review',
      'progress_label': 'Progress',
      'offline_badge_label': 'Downloaded',
      'unenroll_button_label': 'Remove from list',
      'course_unavailable_label': 'Currently unavailable',
      'no_active_courses': 'No active courses',
      'start_learning_message': 'Start by adding courses from the home screen',
      'keep_learning_message': 'Keep learning to complete your courses!',
      'confirm_delete_title': 'Confirm Delete',
      'confirm_delete_message': 'Do you want to remove this course from your list?',
      'error_label': 'Error',
      'buy_now': 'Buy Now',
      'enrolled_already': 'You are enrolled in this course',
      'pending_request': 'Your request is pending',
      'download_course': 'Download Course',
      'get_certificate': 'Get Certificate',
      'lesson': 'Lesson',
      'exam': 'Exam',
      'free': 'Free',
      'certificate_ready': 'Certificate is ready!',
      'premium_course': 'Premium Course',
      'no_instructor_profile': 'No instructor profile available',
      'instructor_title': 'Instructor',
      'lessons_count_label': 'Lessons',
      'reviews_count_label': 'Reviews',
      'students_count_label': 'Students',
      'duration_label': 'Hours',
      'hours_short': 'H',
      'duration': 'Duration',
      'accredited_by': 'Accredited by',
      'no_reviews_yet': 'No reviews yet',
      'add_review': 'Add your review',
      'your_comment_here': 'Write your comment here...',
      'publish': 'Publish',
      'adding_review': 'Adding review...',
      'review_added_success': 'Your review has been added successfully',
      'no_lessons_yet': 'No lessons yet',
      'course_content_working': 'Content is being added to this course soon.',
      'other_lessons': 'Other Lessons',
      'course_content': 'Course Content',
      'must_complete_previous': 'You must complete the previous lesson first',
      'description_tab': 'Description',
      'attachments_tab': 'Attachments',
      'interactive_tab': 'Interactive',
      'exams_tab': 'Exams',
      'notes_tab': 'Notes',
      'questions_tab': 'Questions',
      'lesson_prefix': 'Lesson',
      'starting_download': 'Preparing file...',
      'download_success_encrypted': 'File prepared successfully',
      'download_error': 'Download error',
      'delete_note': 'Delete Note',
      'delete_note_confirm': 'Are you sure you want to delete this note?',
      'note_deleted_success': 'Note deleted successfully',
      'edit_note': 'Edit Note',
      'no_video_available': 'No video available for this lesson',
      'no_interactive_content': 'No interactive content for this lesson',
      'recent_exam_attempts': 'Recent Student Attempts',
      'no_recent_attempts': 'No recent attempts',
      'must_subscribe': 'You must subscribe to the course to watch this lesson',
      'no_exam_at_all': 'No exam for this lesson. Moving to next...',
      'must_take_exam': 'You must pass the exam for this lesson first',
      'start_exam': 'Start Exam',
      'ai_assistant': 'AI Assistant',
      'ai_assistant_coming_soon':
          'AI features will be available in a future update',
      'ai_features_notice':
          'We are working on integrating AI technologies to enhance your learning experience.',
      'view_details': 'View Details',
      'order_report': 'Order Report',
      'details': 'Details',
      'transaction_id': 'Transaction ID',
      'payment_method': 'Payment Method',
      'phone_number': 'Phone Number',
      'order_date': 'Order Date',
      'total_amount': 'Total Amount',
      'status': 'Status',
      'order_number': 'Order Number',
      'app_updates': 'App Updates',
      'manage_app_updates': 'Manage App Updates',
      'version_name': 'Version Name',
      'download_url': 'Download URL',
      'release_notes': 'Release Notes',
      'is_mandatory_label': 'Mandatory Update',
      'add_update': 'Add New Update',
      'update_success': 'Update added successfully',
      'mandatory': 'Mandatory',
      'optional': 'Optional',
      'show_all': 'Show All',
      'discount_percentage': 'Discount Percentage (%)',
      'enter_discount': 'Enter discount percentage',
      'discount_range_error': 'Percentage must be between 0 and 100',
      'manage_my_courses': 'Manage My Courses',
      'manage_courses': 'Manage Courses',
      'total_courses_count': 'Total {count} Courses',
      'general_specialization': 'General Specialization',
      'published': 'Published',
      'draft': 'Draft',
      'unspecified_teacher': 'Unspecified Teacher',
      'exams': 'Exams',
      'edit': 'Edit',
      'no_courses_current': 'No courses found',
      'start_adding_first_course': 'Start by adding the first educational course',
      'delete_course_title': 'Delete Course',
      'delete_course_confirm': 'Are you sure you want to delete this course? All associated lessons will be deleted.',
      'close': 'Close',
      'subscribers': 'Subscribers',
      'completers': 'Completers',
      'average_progress_label': 'Average Progress',
      'completion_rate_label': 'Completion Rate',
      'course_outcomes': 'Course Outcomes',
      'target_audience': 'Target Audience',
      'own_this_course': 'Own this course for',
      'register_and_get': 'Register for this course and get',
      'unending_views': 'Unlimited views',
      'contact_coach': 'Contact with coach',
      'completion_certificate': 'Course completion certificate',
      'or': 'Or',
      'subscribe_now_prefix': 'Enroll Now - ',
      'all_levels': 'All Levels',
      'beginner': 'Beginner',
      'intermediate': 'Intermediate',
      'expert': 'Expert',
      'decision_making': 'Decision Making',
      'goal_achievement': 'Goal Achievement',
      'self_development': 'Self Development',
      'order_priorities': 'Prioritize',
      'body_language': 'Body Language',
      'edit_course': 'Edit Course',
      'create_new_course': 'Create New Course',
      'select_teacher': 'Select Responsible Teacher',
      'search_teacher': 'Search for teacher...',
      'pricing_time_data': 'Pricing & Time Details',
      'free_course': 'Free Course',
      'free_course_desc': 'All students will be able to access it for free',
      'price': 'Price',
      'price_hint': '0 for free',
      'currency': 'Currency',
      'instructor_and_visibility': 'Instructor & Visibility',
      'unspecified': 'Unspecified',
      'is_published_label': 'Status: Published',
      'subject_label': 'Subject',
      'subject_hint': 'Example: Physics',
      'error_enter_subject': 'Please enter the subject name',
      'level_label': 'Level',
      'tags_optional_label': 'Tags (Optional):',
      'basic_info_label': 'Basic Information',
      'course_title_label': 'Course Title',
      'course_title_hint': 'Example: Advanced Math Course',
      'error_enter_title': 'Please enter the course title',
      'course_description_hint': 'Detailed description of the course content',
      'error_enter_description': 'Please enter the course description',
      'course_category_label': 'Course Category',
      'select_category_label': 'Select Category',
      'course': 'Course',
      'welcome_to_doraty': 'Welcome to Doraty Platform',
      'select_account_type': 'Please select your account type to continue',
      'join_as_student': 'Join as Student',
      'student_desc': 'Browse courses and learn new skills',
      'join_as_teacher': 'Join as Teacher',
      'teacher_desc': 'Publish your courses and start teaching',
      'first_name_label': 'First Name',
      'last_name_label': 'Last Name',
      'username_label': 'Username',
      'email_label': 'Email',
      'password_label': 'Password',
      'confirm_password_label': 'Confirm Password',
      'terms_accept_label': 'I agree to the Terms and Conditions',
      'personal_info': 'Personal Information',
      'educational_info_header': 'Educational Information',
      'security_header': 'Security',
      'required_suffix': '(Required)',
      'invalid_email': 'Invalid Email',
      'pass_min_char': 'At least 6 characters',
      'pass_dont_match': 'Passwords do not match',
      'grade_level_label': 'Grade Level',
      'university_specialization_label': 'University Specialization',
      'academic_year_label': 'Academic Year',
      'required_field': 'Required',
      'register_new_coach': 'Register New Coach',
      'participation_plans': 'Participation Plans',
      'participation_intent_label': 'I want to join the platform for (Required):',
      'phone_number_label': 'Phone Number',
      'country_label': 'Country',
      'specialization_label': 'Specialization',
      'give_full_courses_label': 'Give Full Courses',
      'teach_private_hours_label': 'Teach Private Tutoring',
      'cv_label': 'CV / Resume',
      'certificates_label': 'Academic Certificates',
      'short_bio_hint': 'Brief bio about yourself',
      'success_submit_teacher': 'Your application has been submitted successfully! We will review it and get back to you soon.',
      'select_sub_type_error': 'Please select a subscription type (Courses or Tutoring)',
      'fail_get_user_id': 'Failed to get user ID',
      'no_file_selected': 'No file selected (Max 5MB)',
      'change': 'Change',
      'choose': 'Choose',
      'submit_request': 'Submit Request',
      'create_account': 'Create Account',
      'school': 'School',
      'university': 'University',
      'save_changes': 'Save Changes',
      'course_created_success': 'Course created successfully',
      'course_updated_success': 'Course updated successfully',
      'error_saving_data': 'Error saving data',
      'select_at_least_one_category': 'Please select at least one category',
      'register_title': 'Register New Account',
      'register_subtitle': 'Join us and start your learning journey',
      'student_role': 'Student',
      'teacher_role': 'Teacher',
      'register_action': 'Create Account',
      'already_have_account': 'Already have an account?',
      'login_now': 'Login Now',
      'or_via': 'Or via',
      'account_created_success': 'Account created successfully! Welcome',
    },
  };

  static String get(String key, String lang) {
    return _localizedValues[lang]?[key] ?? _localizedValues['ar']?[key] ?? key;
  }
}
