class AppStrings {
  static const Map<String, Map<String, String>> _localizedValues = {
    'ar': {
      'cart_title': 'سلة المشتريات',
      'empty_cart_msg': 'السلة فارغة حالياً',
      'browse_to_add': 'تصفح الدورات وأضفها إلى سلتك',
      'browse_courses': 'تصفح الدورات',
      'checkout': 'إتمام الشراء',
      'total_amount': 'الإجمالي',
      'cart_items_count': 'عدد المنتجات',
      'subscribe_now_prefix': 'اشترك الآن بـ ',
      'register_and_get': 'سجل الآن واحصل على',
      'unending_views': 'مشاهدات غير محدودة',
      'completion_certificate': 'شهادة إتمام معتمدة',
      'contact_coach': 'تواصل مباشر مع المدرب',
      'settings': 'الإعدادات',
      'profile': 'الملف الشخصي',
      'name': 'الاسم',
      'change_photo': 'تغيير الصورة',
      'theme': 'المظهر',
      'display_mode': 'وضع العرض',
      'light': 'فاتح',
      'dark': 'داكن',
      'system': 'تلقائي',
      'notifications': 'الإشعارات',
      'enable_notifications': 'تفعيل الإشعارات',
      'notifications_desc': 'استقبال إشعارات الدروس والاختبارات',
      'by_prefix': 'بواسطة',
      'video_quality': 'جودة الفيديو',
      'about_app': 'عن التطبيق',
      // Course related strings
      'start_course_now': 'ابدأ الدورة الآن',
      'trainer': 'مدرب',
      'course': 'دورة',
      'student': 'طالب',
      'about_trainer': 'نبذة عن المدرب',
      'no_bio_available': 'لا توجد نبذة متاحة حالياً.',
      'no_courses_available': 'لا توجد دورات متاحة',
      'scan_qr_to_activate_course': 'امسح رمز QR لتفعيل الدورة مباشرة',
      'course_eval': 'ما تقييمك للدورة؟',
      'finished_all_course_lessons': 'أحسنت! لقد أكملت جميع دروس الدورة',
      'finish_lesson_and_course': 'إكمال الدرس وإنهاء الدورة',
      'course_removed_from_favorites': 'تم حذف الدورة من المفضلة',
      'no_favorites_yet':
          'لم تضف أي دورة للمفضلة بعد\nاضغط على ❤️ في أي دورة لإضافتها هنا',
      'course_link_copied': 'تم نسخ رابط الدورة! يمكنك مشاركته الآن.',
      'course_enrollments': 'اشتراكات الدورة',
      'course_enrollments_report': 'تقرير اشتراكات الدورة',
      'link_to_specific_course': 'اربط بدورة معينة (CTA)',
      'error_loading_course': 'خطأ في تحميل الدورة',
      'enter_course_desc': 'الرجاء إدخال وصف الدورة',
      'publish_course': 'نشر الدورة',
      'make_course_available': 'جعل الدورة متاحة للطلاب على التطبيق',
      'choose_one_course_min': 'الرجاء اختيار دورة واحدة على الأقل',
      'unknown_course': 'دورة غير معروفة',
      'course_completion_cert': 'شهادة إتمام دورة',
      'successfully_completed_course': 'قد أتم بنجاح دورة',
      'teacher_already_linked': 'المدرس مرتبط بالفعل بهذه الدورة',
      'course_select_required': 'الرجاء اختيار الدورة',
      'version': 'الإصدار',
      'privacy_policy': 'سياسة الخصوصية',
      'terms_conditions': 'شروط الاستخدام',
      'language': 'اللغة',
      'app_language': 'لغة التطبيق',
      'educational_info': 'معلومات تعليمية',
      'professional_info': 'معلومات مهنية',
      'education_level': 'المستوى التعليمي',
      'grade': 'الصف/السنة',
      'specialization': 'التخصص',
      'bio': 'نبذة تعريفية',
      'country': 'البلد',
      'logout': 'تسجيل الخروج',
      'logout_confirm_title': 'تسجيل الخروج',
      'logout_confirm_desc': 'هل أنت متأكد من تسجيل الخروج؟',
      'cancel': 'إلغاء',
      'save': 'حفظ',
      'edit_name': 'تعديل الاسم',
      'enter_full_name': 'أدخل الاسم الكامل',
      'choose_photo': 'اختيار الصورة',
      'camera': 'الكاميرا',
      'gallery': 'معرض الصور',
      'video_quality_high': 'عالية',
      'video_quality_medium': 'متوسطة',
      'video_quality_low': 'منخفضة',
      'clear': 'مسح',
      'error_loading': 'خطأ في تحميل البيانات',
      'changes_saved': 'تم حفظ التغييرات',
      'error_saving': 'خطأ في حفظ التغييرات',
      'error_image_pick': 'خطأ في اختيار الصورة',
      'error_image_upload': 'خطأ في رفع الصورة',
      'error_logout': 'خطأ في تسجيل الخروج',
      'contact_support': 'تواصل مع الدعم',
      'support_desc': 'الدعم الفني والمساعدة',
      'delete_account': 'حذف الحساب',
      'delete_account_desc': 'حذف حسابك وجميع بياناتك نهائياً',
      'delete_confirm_title': 'حذف الحساب',
      'delete_confirm_desc':
          'هل أنت متأكد من رغبتك في حذف حسابك؟ هذا الإجراء لا يمكن التراجع عنه.',
      'delete': 'حذف',
      'support_dialog_title': 'الدعم الفني',
      'support_dialog_desc': 'يمكنك التواصل معنا عبر الوسائل التالية:',
      'email_us': 'راسلنا عبر البريد الإلكتروني',
      'whatsapp_us': 'تواصل معنا عبر واتساب',
      'home': 'الرئيسية',
      'explore': 'تصفح',
      'my_courses': 'دوراتي',
      'welcome': 'أهلاً بك يا ضيف',
      'guest': 'ضيف',
      'searching': 'ابحث عن درسك التالي...',
      'categories': 'التصنيفات',
      'all': 'الكل',
      'top_teachers': 'أفضل المدربين',
      'continue_watching': 'متابعة المشاهدة',
      'explore_more': 'تصفح المزيد',
      'search_courses': 'البحث عن الدورات',
      'search_hint': 'ابحث باسم الدورة أو المعلم...',
      'filter': 'تصفية',
      'filter_by_category': 'تصفية حسب التصنيف',
      'edit_profile': 'تعديل الملف الشخصي',
      'statistics': 'الإحصائيات',
      'joined': 'انضم في',
      'completed_courses': 'الدورات المكتملة',
      'hours_spent': 'ساعات الدراسة',
      'no_courses_found': 'لم يتم العثور على دورات',
      'try_different_search': 'حاول البحث بكلمات مختلفة',
      'featured_courses': 'دورات مميزة',
      'no_featured_courses_message':
          'لم يتم العثور على أي دورات مميزة في الوقت الحالي.',
      'welcome_with_name': 'أهلاً بك يا',
      'ready_to_learn': 'جاهز للتعلم؟',
      'search_course_hint': 'ابحث عن دورة...',
      'continue_learning': 'تابع التعلم',
      'completed': 'اكتمل',
      'featured_course_badge': 'دورة مميزة',
      'most_popular': 'الأكثر طلباً',
      'teacher': 'مدرس',
      'explore_courses': 'استكشف الدورات',
      'no_courses_in_category': 'لا توجد دورات في هذا القسم',
      'no_categories_found': 'لم يتم العثور على تصنيفات',
      'loading': 'جاري التحميل...',
      'current_courses': 'دوراتي الحالية',
      'completed_status': 'مكتملة',
      'enrolled': 'مسجل',
      'no_current_courses': 'لا توجد دورات حالية',
      'no_completed_courses': 'لا توجد دورات مكتملة بعد',
      'unenroll_confirm': 'هل أنت متأكد من إلغاء التسجيل؟',
      'unenroll_success': 'تم إزالة الدورة من قائمتك',
      'unenroll_error': 'حدث خطأ أثناء إلغاء التسجيل',
      'course_removed': 'تم إزالة الدورة بنجاح',
      'no_current_courses_desc': 'ابدأ بتصفح الدورات وسجل في اهتماماتك!',
      'no_completed_courses_desc':
          'بمجرد إنهاء الدورة، ستظهر هنا في قائمة المكتملة.',
      'current': 'الحالية',
      'admin_dashboard': 'لوحة تحكم المشرف',
      'teacher_dashboard': 'لوحة تحكم الأستاذ',
      'account_upgrades': 'ترقيات الحساب',
      'certificates': 'شهادات',
      'learning_hours': 'ساعة تعلم',
      'orders': 'طلباتي',
      'dashboard': 'لوحة التحكم',
      'financial_reports': 'التقارير المالية',
      'my_financial_report': 'تقريري المالي',
      'all_teachers': 'جميع المدربين',
      'total_revenue': 'إجمالي الأرباح',
      'total_enrollments': 'إجمالي التسجيلات',
      'performance_summary': 'ملخص الأداء',
      'performance_summary_title': 'لوحة ملخص الأداء',
      'attempt_unit_label': 'محاولة',
      'total_revenue_label': 'إجمالي الأرباح (ريال)',
      'total_attempts_title': 'إجمالي الاختبارات',
      'course_unit_label': 'دورة',
      'student_label': 'طالب',
      'active_users_label': 'النشطين أسبوعياً',
      'weekly_growth_label': 'النمو الأسبوعي',
      'active_students': 'الطلاب النشطون',
      'courses_count': 'عدد الكورسات',
      'user': 'المستخدم',
      'completed_courses_count_label': 'دورة مكتملة',
      'no_orders_yet': 'لا توجد طلبات سابقة',
      'no_orders_desc': 'لم تقم بشراء أي دورات بعد. جميع فواتيرك ستظهر هنا.',
      'study_continue': 'استمر في الدراسة!',
      'courses_not_completed_desc':
          'لم تكمل أي دورة بالكامل حتى الآن. استمر في الدراسة!',
      'enrolled_courses_desc':
          'ابدأ رحلتك التعليمية اليوم واستكشف دوراتنا المتاحة.',
      'no_courses_yet': 'لم تشتر أي دورة بعد',
      'course_description': 'وصف الدورة',
      'curriculum_tab': 'المنهاج',
      'reviews_tab': 'التقييمات',
      'buy_now': 'اشترِ الآن',
      'enrolled_already': 'أنت مسجل في هذه الدورة',
      'pending_request': 'طلبك قيد المراجعة',
      'get_certificate': 'الحصول على الشهادة',
      'lesson': 'درس',
      'enter_course': 'الدخول إلى الدورة',
      'exam': 'اختبار',
      'free': 'مجاني',
      'certificate_ready': 'الشهادة جاهزة!',
      'premium_course': 'دورة مميزة',
      'no_instructor_profile': 'لا يوجد ملف شخصي لهذا المدرب حالياً',
      'instructor_title': 'الأستاذ',
      'reviews_count_label': 'تقييم',
      'reviews_label': 'تقييم',
      'progress_label': 'التقدم',
      'unenroll_button_label': 'حذف من قائمتي',
      'course_unavailable_label': 'هذه الدورة غير متاحة حالياً',
      'no_active_courses': 'لا توجد دورات حالية',
      'start_learning_message': 'ابدأ بإضافة دورات من الصفحة الرئيسية',
      'keep_learning_message': 'استمر في التعلم لإكمال دوراتك!',
      'confirm_delete_title': 'تأكيد الحذف',
      'confirm_delete_message': 'هل تريد إزالة هذه الدورة من قائمتك؟',
      'error_label': 'خطأ',
      'lessons_count_label': 'درس',
      'lessons': 'درساً',
      'chapters': 'فصلاً',
      'bundles_label': 'باقات مترابطة',
      'no_bundles_available': 'لا توجد باقات متاحة حالياً',
      'students_count_label': 'طالب',
      'duration_label': 'ساعة',
      'hours_short': 'ساعة',
      'duration': 'المدة',
      'accredited_by': 'معتمد من قبل',
      'no_reviews_yet': 'لا توجد تقييمات بعد',
      'reviews': 'تقييمات',
      'add_review': 'أضف تقييمك',
      'reviewed_already': 'لقد قمت بتقييم هذه الدورة',
      'be_first_to_review':
          'كن أول من يقيم هذه الدورة ويشارك تجربته مع الآخرين',
      'anonymous_user': 'مستخدم',
      'your_comment_here': 'اكتب تعليقك هنا...',
      'publish': 'نشر',
      'adding_review': 'جاري إضافة التقييم...',
      'review_added_success': 'تم إضافة تقييمك بنجاح',
      'no_lessons_yet': 'لا توجد دروس حالياً',
      'read_more': 'اقرأ المزيد',
      'read_less': 'اقرأ أقل',
      'similar_courses': 'دورات مشابهة',
      'view_all_reviews': 'عرض جميع التقييمات والآراء',
      'course_content_working': 'يتم العمل على إضافة محتوى لهذه الدورة قريباً.',
      'other_lessons': 'دروس أخرى',
      'course_content': 'محتوى الدورة',
      'must_complete_previous': 'يجب إكمال الدرس السابق أولاً',
      'description_tab': 'الوصف',
      'attachments_tab': 'المرفقات',
      'interactive_tab': 'تفاعل',
      'exams_tab': 'اختبارات',
      'notes_tab': 'الملاحظات',
      'questions_tab': 'الأسئلة',
      'lesson_prefix': 'الدرس',
      'delete_note': 'حذف الملاحظة',
      'delete_note_confirm': 'هل أنت متأكد من رغبتك في حذف هذه الملاحظة؟',
      'note_deleted_success': 'تم حذف الملاحظة بنجاح',
      'edit_note': 'تعديل الملاحظة',
      'no_video_available': 'لا يوجد فيديو لهذا الدرس',
      'no_interactive_content': 'لا يوجد محتوى تفاعلي مخصص لهذا الدرس',
      'recent_exam_attempts': 'أحدث محاولات الطلاب',
      'no_recent_attempts': 'لا توجد محاولات حديثة',
      'must_subscribe': 'يجب الاشتراك في المادة لمشاهدة هذا الدرس',
      'no_exam_at_all': 'لا يوجد اختبار لهذا الدرس. الانتقال للدرس التالي...',
      'must_take_exam': 'يجب اجتياز اختبار هذا الدرس أولاً',
      'start_exam': 'بدء الاختبار',
      'ai_assistant': 'المساعد الذكي',
      'ai_assistant_coming_soon': 'ستتاح ميزة الذكاء الاصطناعي في تحديث قادم',
      'ai_features_notice':
          'نحن نعمل على دمج تقنيات الذكاء الاصطناعي لتعزيز تجربتك التعليمية.',
      'view_details': 'عرض التفاصيل',
      'order_report': 'تقرير الطلب',
      'details': 'التفاصيل',
      'transaction_id': 'رقم العملية',
      'phone_number': 'رقم الهاتف',
      'order_date': 'تاريخ الطلب',
      'status': 'الحالة',
      'order_number': 'رقم الطلب',
      'app_updates': 'تحديثات التطبيق',
      'all_categories': 'جميع الأقسام',
      'category_label': 'القسم',
      'manage_app_updates': 'إدارة تحديثات النظام',
      'version_name': 'رقم الإصدار',
      'download_url': 'رابط التحميل',
      'release_notes': 'ملاحظات الإصدار',
      'is_mandatory_label': 'تحديث إجباري',
      'add_update': 'إضافة تحديث جديد',
      'update_success': 'تم إضافة التحديث بنجاح',
      'mandatory': 'إجباري',
      'optional': 'اختياري',
      'show_all': 'عرض الكل',
      'discount_percentage': 'نسبة الخصم (%)',
      'enter_discount': 'أدخل نسبة الخصم',
      'discount_range_error': 'يجب أن تكون النسبة بين 0 و 100',
      'manage_my_courses': 'إدارة دوراتي',
      'manage_courses': 'إدارة الدورات',
      'courses_count_title': 'دورة',
      'total_courses_count': 'إجمالي {count} دورة تعليمية',
      'general_specialization': 'تخصص عام',
      'categories_title': 'الفئات',
      'search': 'بحث',
      'published': 'منشور',
      'draft': 'مسودة',
      'unspecified_teacher': 'مدرس غير محدد',
      'current_teachers': 'المدربين الحاليين',
      'pending_requests': 'طلبات الانتظار',
      'teachers_management_title': 'إدارة شؤون المدربين',
      'exams': 'الاختبارات',
      'edit': 'تعديل',
      'no_courses_current': 'لا توجد دورات حالياً',
      'start_adding_first_course': 'ابدأ بإضافة أول دورة تعليمية للمنصة',
      'delete_course_title': 'حذف الدورة',
      'delete_course_confirm':
          'هل أنت متأكد من حذف هذه الدورة؟ سيتم حذف جميع الدروس المرتبطة بها.',
      'close': 'إغلاق',
      'subscribers': 'المشتركين',
      'completers': 'المكملين',
      'average_progress_label': 'متوسط التقدم',
      'completion_rate_label': 'معدل الإكمال',
      'no_sessions_yet': 'لا توجد جلسات مجدولة حالياً',
      'live_sessions': 'جلسات البث المباشر',
      'watch_recording': 'مشاهدة التسجيل',
      'join': 'انضمام الآن',
      'sessions_tab': 'الجلسات والمواعيد',
      'location': 'الموقع',
      'recorded': 'مسجلة',
      'live': 'مباشر',
      'in_person': 'حضوري',
      'recorded_desc': 'دورة مسجلة كاملة يمكنك البدء بها في أي وقت',
      'live_desc': 'بث مباشر تفاعلي مع المدرب في مواعيد محددة',
      'in_person_desc': 'دورة حضورية في مقر المعهد أو المركز',
      'course_outcomes': 'نتائج الدورة',
      'target_audience': 'الفئة المستهدفة',
      'own_this_course': 'امتلك الدورة بـ',
      'course_register_and_get': 'سجل بهذه الدورة واحصل على',
      'course_unending_views': 'مشاهدة غير محدودة للدورة',
      'course_contact_coach': 'التواصل مع المدرب',
      'course_completion_certificate': 'شهادة إتمام الدورة',
      'or': 'أو',
      'course_subscribe_now_prefix': 'اشترك الآن - ',
      'all_levels': 'جميع المستويات',
      'beginner': 'مبتدئ',
      'intermediate': 'متوسط',
      'advanced': 'متقدم',
      'expert': 'احترافي',
      'decision_making': 'اتخاذ القرار',
      'goal_achievement': 'تحقيق اهداف',
      'self_development': 'تطوير الذات',
      'order_priorities': 'تنظيم اولويات',
      'body_language': 'لغة الجسد',
      'edit_course': 'تعديل الدورة',
      'create_new_course': 'إنشاء دورة جديدة',
      'select_teacher': 'اختر المدرس المسئول',
      'search_teacher': 'بحث عن مدرس...',
      'pricing_time_data': 'بيانات التسعير والوقت',
      'free_course': 'دورة مجانية',
      'free_course_desc': 'سيتمكن جميع الطلاب من الوصول إليها بدون دفع',
      'price': 'السعر',
      'price_hint': '0 للمجاني',
      'currency': 'العملة',
      'instructor_and_visibility': 'المدرس والظهور',
      'unspecified': 'غير محدد',
      'is_published_label': 'الحالة: منشور',
      'subject_label': 'المادة',
      'subject_hint': 'مثال: فيزياء',
      'error_enter_subject': 'الرجاء إدخال اسم المادة',
      'tags_optional_label': 'الوسوم (اختياري):',
      'basic_info_label': 'المعلومات الأساسية',
      'course_image_url': 'رابط صورة الدورة',
      'image_url_hint': 'https://example.com/image.jpg',
      'video_url_label': 'رابط الفيديو التعريفي',
      'video_url_hint': 'https://vimeo.com/... أو رابط مباشر',
      'course_title_label': 'عنوان الدورة',
      'course_title_hint': 'مثال: دورة الرياضيات المتقدمة',
      'error_enter_title': 'الرجاء إدخال عنوان الدورة',
      'course_description_hint': 'وصف مفصل عن محتوى الدورة',
      'error_enter_description': 'الرجاء إدخال وصف الدورة',
      'course_category_label': 'تصنيف الدورة',
      'select_category_label': 'اختر التصنيف',
      'welcome_to_doraty': 'أهلاً بك في منصة دوراتي',
      'select_account_type': 'الرجاء اختيار نوع حسابك للمتابعة',
      'join_as_student': 'انضم كطالب',
      'student_desc': 'تصفح الدورات وتعلم مهارات جديدة',
      'join_as_teacher': 'انضم كمدرب',
      'teacher_desc': 'انشر دوراتك وابدأ بالتدريب',
      'first_name_label': 'الاسم الأول',
      'last_name_label': 'الاسم الأخير',
      'username_label': 'اسم المستخدم',
      'email_label': 'البريد الإلكتروني',
      'password_label': 'كلمة المرور',
      'confirm_password_label': 'تأكيد كلمة المرور',
      'terms_accept_label': 'أنا موافق على الشروط والأحكام',
      'personal_info': 'المعلومات الشخصية',
      'educational_info_header': 'المعلومات التعليمية',
      'security_header': 'الأمان',
      'required_suffix': '(مطلوب)',
      'invalid_email': 'بريد غير صحيح',
      'pass_min_char': '6 أحرف على الأقل',
      'pass_dont_match': 'كلمات المرور لا تتطابق',
      'grade_level_label': 'المرحلة الدراسية',
      'university_specialization_label': 'التخصص الجامعي',
      'academic_year_label': 'السنة الدراسية',
      'required_field': 'مطلوب',
      'register_new_coach': 'تسجيل مدرب جديد',
      'participation_plans': 'خطط المشاركة',
      'participation_intent_label': 'أرغب في الاشتراك في المنصة في (مطلوب):',
      'phone_number_label': 'رقم الجوال',
      'country_label': 'البلد',
      'specialization_label': 'التخصص',
      'give_full_courses_label': 'إعطاء دورات كاملة',
      'teach_private_hours_label': 'تدريس ساعات خصوصية',
      'cv_label': 'السيرة الذاتية',
      'certificates_label': 'الشهادات العلمية',
      'short_bio_hint': 'نبذة قصيرة عنك',
      'success_submit_teacher':
          'تم إرسال طلبك بنجاح! سنقوم بمراجعته والرد عليك قريباً',
      'select_sub_type_error':
          'الرجاء اختيار نوع الاشتراك (دورات أو ساعات خصوصية)',
      'fail_get_user_id': 'فشل الحصول على معرف المستخدم',
      'no_file_selected': 'لم يتم اختيار ملف (الحد الأقصى 5MB)',
      'change': 'تغيير',
      'choose': 'اختيار',
      'submit_request': 'تقديم الطلب',
      'create_account': 'إنشاء الحساب',
      'school': 'مدرسة',
      'university': 'جامعة',
      'save_changes': 'حفظ التعديلات',
      'course_created_success': 'تم إنشاء الدورة بنجاح',
      'course_updated_success': 'تم تحديث الدورة بنجاح',
      'error_saving_data': 'خطأ في حفظ البيانات',
      'select_at_least_one_category': 'الرجاء اختيار تصنيف واحد على الأقل',
      'error_select_teacher': 'يرجى اختيار المدرب',
      'error_select_level': 'يرجى اختيار مستوى الدورة',
      'error_select_category': 'يرجى اختيار تصنيف واحد على الأقل',
      'register_title': 'إنشاء حساب جديد',
      'register_subtitle': 'انضم إلينا وابدأ رحلتك التعليمية',
      'student_role': 'طالب',
      'teacher_role': 'مدرب',
      'register_action': 'إنشاء الحساب',
      'already_have_account': 'لديك حساب بالفعل؟',
      'login_now': 'سجل دخولك الآن',
      'or_via': 'أو عبر',
      'account_created_success': 'تم إنشاء الحساب بنجاح! مرحباً بك',
      'bundle_badge': 'باقة',
      'courses_count_bundle': 'دورات',
      'all_bundles': 'جميع الباقات',
      'bundle_details': 'تفاصيل الباقة',
      'included_courses': 'الدورات المشمولة',
      'buy_bundle': 'امتلك الباقة',
      'featured_bundles': 'باقات مميزة',
      'login_title': 'تسجيل الدخول',
      'login_required_title': 'تسجيل الدخول مطلوب',
      'login_required_desc':
          'يرجى تسجيل الدخول للوصول إلى ملفك الشخصي ومتابعة دوراتك',
      'offline_mode': 'وضع الأوفلاين (بيانات مخزنة)',
      'ad_banner_title': 'خطط دراسية متميزة',
      'ad_banner_subtitle': 'اشترك بـ باقة دورات ووفر أكثر من 50%',
      'view_plans_button': 'عرض الخطط',
      'new_courses': 'دورات جديدة',
      'most_watched': 'الأكثر مشاهدة',
      'recorded_courses': 'الدورات المحملة',
      'learning_tips_title': 'نصائح دراسية',
      'tips': 'نصائح',
      'bundles_title': 'باقات مميزة',
      'hello': 'أهلاً بك',
      'my_receipts': 'إيصالاتي',
      'favorites': 'المفضلة',
      'faq': 'الأسئلة الشائعة',
      'dark_mode_title': 'الوضع الليلي',
      'banners_management': 'إدارة الإعلانات',
      'no_banners_found': 'لا يوجد إعلانات حالياً',
      'add_banner': 'إضافة إعلان جديد',
      'faq_search_hint': 'ابحث عن سؤال...',
      'faq_how_subscribe': 'كيف يمكنني الاشتراك في دورة؟',
      'faq_how_subscribe_ans':
          'يمكنك اختيار الدورة التي تريدها، ثم الضغط على زر "اشترك" في الأسفل، وإكمال عملية الدفع.',
      'faq_payment_methods': 'ما هي طرق الدفع المتاحة؟',
      'faq_payment_methods_ans':
          'ندعم حالياً التحويل البنكي، والدفع عند الاستلام في مراكزنا، وسنضيف قريباً الدفع الإلكتروني.',
      'faq_certificate': 'هل أحصل على شهادة بعد إتمام الدورة؟',
      'faq_certificate_ans':
          'نعم، ستحصل على شهادة إتمام إلكترونية فور إنهاء جميع دروس الدورة والاختبارات الملحقة بها.',
      'faq_contact_teacher': 'كيف يمكنني التواصل مع المدرب؟',
      'faq_contact_teacher_ans':
          'يمكنك طرح استفساراتك عبر قسم التعليقات في صفحة الدرس، أو عبر الرسائل المباشرة مع المدرب.',
      'faq_support': 'كيف أتواصل مع الدعم الفني؟',
      'faq_support_ans':
          'يمكنك التواصل معنا عبر صفحة "تواصل مع الدعم" الموجودة في القائمة الجانبية.',
      // Admin Dashboard
      'admin_users': 'المستخدمين',
      'admin_users_desc': 'إدارة جميع مستخدمي المنصة',
      'admin_categories': 'التصنيفات',
      'admin_categories_desc': 'إدارة تصنيفات الدورات',
      'admin_teachers': 'شؤون المدرسين',
      'admin_teachers_desc': 'إدارة المدربين وطلبات الانضمام',
      'admin_bundles': 'الباقات',
      'admin_bundles_desc': 'إدارة باقات الدورات',
      'admin_tips_side': 'نصائح العمل',
      'admin_tips_desc': 'إدارة نصائح الفيديو القصيرة',
      'admin_banners_side': 'الإعلانات',
      'admin_banners_desc': 'إدارة صور البنر المتحركة',
      'admin_courses_desc': 'إدارة محتوى الدورات',
      'course_lessons': 'دروس الدورة',
      'add_lesson': 'إضافة درس',
      'minutes_unit': 'دقيقة',
      'exams_label': 'الاختبارات:',
      'add_exam': 'إضافة اختبار',
      'order_updated': 'تم تحديث الترتيب',
      'delete_lesson_confirm': 'هل أنت متأكد من حذف هذا الدرس؟',
      'edit_chapter': 'تعديل الفصل',
      'no_chapters_yet': 'لا توجد فصول بعد',
      'manage_chapters': 'إدارة الفصول',
      'delete_lesson': 'حذف الدرس',
      'lesson_removed': 'تم حذف الدرس',
      'delete_chapter': 'حذف الفصل',
      'delete_chapter_confirm': 'هل أنت متأكد؟ ستبقى الدروس ولكن بدون فصل.',
      'add_chapter': 'إضافة فصل',
      'add_new': 'إضافة جديد',
      'no_lessons': 'لا توجد دروس',
      'start_adding_first_lesson': 'ابدأ بإضافة الدرس الأول',
      'search_users_hint': 'بحث عن مستخدم...',
      'admin_role_label': 'مدير',
      'teacher_role_label': 'مدرس',
      'student_role_label': 'طالب',
      'assign_role': 'تعيين دور',
      'cannot_edit_admin_roles': 'لا يمكن تعديل أدوار المديرين',
      'role_assigned_success': 'تم تعيين الدور بنجاح',
      'admin_subscriptions_side': 'الاشتراكات',
      'admin_subscriptions_desc': 'متابعة اشتراكات الطلاب',
      'admin_payments_side': 'الدفع',
      'admin_payments_desc': 'مراجعة إيصالات الدفع',
      'admin_payment_settings_side': 'حسابات الدفع',
      'admin_payment_settings_desc': 'تعديل حسابات الدفع',
      'admin_financial_reports': 'التقارير المالية',
      'admin_financial_reports_desc': 'استخراج تقارير الإيرادات',
      'admin_notifications_side': 'الإشعارات',
      'admin_notifications_desc': 'إرسال تنبيهات عامة',
      'admin_qr_side': 'أكواد QR',
      'admin_qr_desc': 'إنشاء أكواد التفعيل',
      'admin_updates_side': 'تحديثات التطبيق',
      'admin_updates_desc': 'إصدار نسخة جديدة',
      'admin_social_links_side': 'حسابات التواصل',
      'admin_social_links_desc': 'إدارة روابط منصات التواصل',
      'social_facebook': 'فيسبوك',
      'social_instagram': 'انستجرام',
      'social_youtube': 'يوتيوب',
      'social_whatsapp': 'واتساب',
      'social_x_twitter': 'منصة إكس (تويتر)',
      'social_linkedin': 'لينكد إن',
      'social_tiktok': 'تيك توك',
      'social_telegram': 'تيليجرام',
      'social_url_hint': 'ضع الرابط هنا. اتركه فارغاً لإخفائه',
      'admin_security_side': 'إعدادات الأمان',
      'admin_security_desc': 'التحكم في لقطات الشاشة',
      'admin_quick_actions': 'الإجراءات السريعة',
      'admin_recent_attempts': 'أحدث محاولات الطلاب',
      'admin_no_attempts': 'لا توجد محاولات حديثة في سجل النظام',
      'admin_view_all': 'عرض الكل',
      'admin_student': 'طالب',
      'admin_unknown_exam': 'اختبار غير معروف',
      'admin_passed': 'ناجح',
      'admin_failed': 'راسب',
      'title': 'العنوان',
      'financial_report': 'التقرير المالي',
      'platform_name': 'منصة دوراتي التعليمية',
      'period': 'الفترة',
      'print_date': 'تاريخ الطباعة',
      'enrollments_count': 'عدد الاشتراكات',
      'date': 'التاريخ',
      'amount': 'المبلغ',
      'select_period': 'اختر الفترة الزمنية',
      'filter_by_course_optional': 'تصفية حسب الدورة (اختياري)',
      'generate_report': 'استخراج التقرير',
      'tips_management': 'إدارة النصائح',
      'delete_tip': 'حذف النصيحة',
      'delete_tip_confirm': 'هل أنت متأكد من حذف هذه النصيحة؟',
      'tip_deleted_success': 'تم حذف النصيحة بنجاح',
      'no_tips_found': 'لا توجد نصائح حالياً',
      'add_first_tip': 'أضف أول نصيحة',
      'views_unit': 'مشاهدة',
      'linked_to_course': 'مرتبط بدورة',
      'new_tip': 'نصيحة جديدة',
      'error_delete_tip': 'خطأ في حذف النصيحة',
      'bundles_management': 'إدارة الباقات',
      'no_bundles_found_admin': 'لا يوجد باقات حالياً',
      'add_new_bundle': 'إضافة باقة جديدة',
      'delete_bundle_confirm': 'هل أنت متأكد من حذف هذه الباقة؟',
      'currency_syp': 'ل.س',
      'yes': 'نعم',
      'no': 'لا',
      'categories_management': 'إدارة التصنيفات',
      'add_category': 'إضافة تصنيف',
      'base_category': 'التصنيف الأساسي',
      'sub_categories': 'التصنيفات الفرعية',
      'no_sub_categories': 'لا توجد تصنيفات فرعية',
      'edit_category': 'تعديل التصنيف',
      'add_new_category': 'إضافة تصنيف جديد',
      'category_name': 'اسم التصنيف',
      'slug_label': 'المعرف (Slug)',
      'icon_url_optional': 'رابط الأيقونة (اختياري)',
      'parent_category_optional': 'التصنيف الأب (اختياري)',
      'main_category': 'تصنيف رئيسي',
      'none_main_category': 'بدون (تصنيف رئيسي)',
      'please_fill_required_fields': 'الرجاء ملء الحقول المطلوبة',
      'delete_category_confirm': 'هل أنت متأكد من حذف هذا التصنيف؟',
      'banners_management_title': 'إدارة الإعلانات والبنرات',
      'no_banners_found_admin': 'لا يوجد إعلانات حالياً',
      'add_new_banner': 'إضافة إعلان جديد',
      'edit_banner': 'تعديل الإعلان',
      'ad_preview': 'معاينة الإعلان',
      'main_title': 'العنوان الرئيسي',
      'subtitle_action_text_optional':
          'العنوان الفرعي / نص زر التفاعل (اختياري)',
      'image_url_label': 'رابط الصورة',
      'image_upload_success': 'تم رفع الصورة بنجاح',
      'error_upload_image': 'خطأ في رفع الصورة',
      'ad_type': 'نوع الإعلان',
      'general_ad': 'إعلان عام',
      'specific_course': 'كورس محدد',
      'bundle_offer': 'باقة / عرض',
      'external_link': 'رابط خارجي',
      'type_label': 'نوع الإعلان',
      'select_course': 'اختر الكورس',
      'select_bundle': 'اختر الباقة',
      'display_location': 'مكان الظهور',
      'main_top': 'رئيسي (أعلى)',
      'secondary_bottom': 'ثانوي (أسفل)',
      'visit_link': 'زيارة الرابط',
      'ad_title_fallback': 'عنوان الإعلان',
      'click_to_select': 'انقر للاختيار...',
      'id_label': 'مُعرّف',
      'delete_banner_confirm': 'هل أنت متأكد من حذف هذا الإعلان؟',
      'search_hint_name_teacher': 'بحث بالاسم أو اسم المعلم...',
      'no_results': 'لا توجد نتائج',
      'location_label': 'المكان',
      'top_location': 'علوي',
      'bottom_location': 'سفلي',
      'no_teachers_found': 'لا يوجد مدربين حالياً',
      'no_pending_requests': 'لا توجد طلبات انضمام معلقة',
      'new_request': 'طلب جديد',
      'approve': 'موافقة',
      'reject': 'رفض',
      'request_approved_success': 'تمت الموافقة على الطلب',
      'request_rejected_success': 'تم رفض الطلب',
      'no_email': 'بدون بريد إلكتروني',
      'manage_courses_btn': 'إدارة الكورسات',
      'create_exam': 'إنشاء اختبار',
      'manage_exams': 'إدارة الاختبارات',
      'unpublish': 'إلغاء النشر',
      'manage_questions': 'إدارة الأسئلة',
      'no_exams_found': 'لا توجد اختبارات',
      'create_exam_prompt': 'ابدأ بإنشاء اختبار جديد لهذه الدورة',
      'unpublish_success': 'تم إلغاء النشر بنجاح',
      'publish_success': 'تم النشر بنجاح',
      'delete_exam_title': 'حذف الاختبار',
      'delete_exam_confirm': 'هل أنت متأكد من حذف هذا الاختبار؟',
      'delete_exam_success': 'تم حذف الاختبار بنجاح',
      'notifications_management': 'إدارة الإشعارات',
      'send_new_notification': 'إرسال إشعار جديد',
      'notification_history': 'سجل الإشعارات المرسلة',
      'send_to': 'إرسال إلى',
      'all_users': 'جميع المستخدمين',
      'specific_course_students': 'طلاب دورة محددة',
      'specific_user': 'مستخدم محدد',
      'select_target_error': 'يرجى اختيار المستهدف (دورة أو مستخدم)',
      'notification_sent_success': 'تم الإرسال بنجاح إلى {count} مستخدم',
      'notification_send_failed': 'فشل الإرسال',
      'no_notification_history': 'لا يوجد سجل للإشعارات',
      'notification_title': 'عنوان الإشعار',
      'notification_body': 'نص الإشعار',
      'send_notification_btn': 'إرسال الإشعار',
      'manage_subscriptions': 'إدارة الاشتراكات',
      'print_report': 'طباعة التقرير',
      'revenue': 'الدخل',
      'total_students': 'إجمالي الطلاب',
      'total_students_stat': 'إجمالي الطلاب',
      'search_subscription_hint': 'بحث باسم الطالب أو الدورة...',
      'filter_by_date_all': 'تصفية حسب التاريخ: الكل',
      'filter_prefix': 'تصفية: ',
      'year_prefix': 'سنة ',
      'by_course': 'حسب الدورة',
      'by_teacher': 'حسب المدرس',
      'unassigned_course': 'دورة غير منسوبة',
      'subscription_date': 'تاريخ الاشتراك',
      'cancel_subscription': 'إلغاء الاشتراك',
      'no_matching_subscriptions': 'لا توجد اشتراكات مطابقة',
      'confirm_cancellation': 'تأكيد الإلغاء',
      'cancel_subscription_confirm':
          'هل أنت متأكد من تغيير حالة الاشتراك لهذا الطالب؟ سيؤدي هذا لإلغاء وصوله للمحتوى.',
      'subscription_updated_success': 'تم تحديث حالة الاشتراك بنجاح',
      'select_filter_period': 'اختر فترة التصفية',
      'monthly': 'شهري',
      'yearly': 'سنوي',
      'financial_report_title': 'التقرير المالي',
      'period_prefix': 'الفترة: ',
      'print_date_prefix': 'تاريخ الطباعة: ',
      'fail_generate_report': 'فشل إنشاء التقرير: ',
      'print_all_confirm_desc':
          'لم يتم تحديد فترة تصفية (شهر أو سنة). سيتم طباعة تقرير لجميع الاشتراكات.\nهل تريد المتابعة؟',
      'continue_action': 'متابعة',
      'payment_method': 'طريقة الدفع',
      'cash': 'نقدي',
      'detailed_management': 'إدارة تفصيلية',
      'teacher_stats': 'إحصائيات المدرس',
      'course_count_prefix': 'عدد الكورسات: ',
      'welcome_text': 'مرحباً بك',
      'forgot_password': 'نسيت كلمة المرور؟',
      'dont_have_account': 'ليس لديك حساب؟',
      'register_now': 'سجل الآن',
      'reset_password': 'استعادة كلمة المرور',
      'reset_password_desc':
          'أدخل بريدك الإلكتروني وسنرسل لك رابطاً لتعيين كلمة مرور جديدة.',
      'error_enter_email': 'الرجاء إدخال البريد الإلكتروني',
      'error_enter_password': 'الرجاء إدخال كلمة المرور',
      'reset_password_success':
          'تم إرسال رابط استعادة كلمة المرور إلى بريدك الإلكتروني.',
      'send': 'إرسال',
      'checking_account': 'جاري التحقق من الحساب...',
      'login_canceled': 'تم إلغاء تسجيل الدخول عبر جوجل',
      'cart_content': 'محتوى السلة',
      'discount': 'خصم',
      'subtotal': 'المجموع',
      'add_discount_code': 'إضافة رمز الخصم',
      'complete_registration': 'إتمام عملية التسجيل',
      'course_not_found': 'عذراً، لم يتم العثور على الدورة',
      'upcoming_exams': 'الاختبارات القادمة',
      'no_upcoming_exams': 'لا توجد اختبارات قادمة',
      'completed_exams': 'الاختبارات المكتملة',
      'no_completed_exams': 'لا توجد اختبارات مكتملة',
      'points': 'نقطة',
      'subject_math': 'الرياضيات',
      'subject_physics': 'الفيزياء',
      'subject_chemistry': 'الكيمياء',
      'subject_biology': 'الأحياء',
      'subject_arabic': 'اللغة العربية',
      'subject_english': 'اللغة الإنجليزية',
      'subject_french': 'اللغة الفرنسية',
      'subject_religion': 'الديانة',
      'subject_history': 'التاريخ',
      'subject_geography': 'الجغرافيا',
      'subject_philosophy': 'الفلسفة',
      'subject_sociology': 'علم الاجتماع',
      'high_school_courses_desc': 'دورات {subject} للثانوية العامة',
      'exam_math_title': 'اختبار الفصل الأول - الرياضيات',
      'exam_math_desc':
          'اختبار شامل للفصل الأول يغطي المعادلات التربيعية والتفاضل',
      'exam_math_course': 'الرياضيات المتقدمة',
      'exam_physics_title': 'اختبار الفيزياء - الحركة',
      'exam_physics_desc': 'اختبار على قوانين الحركة والسرعة والتسارع',
      'exam_physics_course': 'الفيزياء',
      'exam_chemistry_title': 'اختبار الكيمياء - الجدول الدوري',
      'exam_chemistry_desc': 'اختبار على عناصر الجدول الدوري وخصائصها',
      'exam_chemistry_course': 'الكيمياء',

      // Exams management
      'exams_management': 'إدارة الاختبارات',
      'minute': 'دقيقة',
      'no_exams': 'لا توجد اختبارات',
      'confirm_delete_exam': 'هل أنت متأكد من حذف هذا الاختبار؟',
      'teacher_dashboard_welcome': 'مرحباً بك في لوحة التحكم',
      'total_income': 'إجمالي الدخل',
      'courses_stat': 'الدورات',
      'exams_stat': 'الاختبارات',
      'quick_actions': 'إجراءات سريعة',
      'student_results': 'نتائج الطلاب',
      'recent_exams': 'الاختبارات الأخيرة',
      'period_label': 'الفترة: ',
      'date_label': 'التاريخ: ',
      'enrollments_stat': 'الاشتراكات',
      'attempts_stat': 'المحاولات',
      'monthly_breakdown': 'التفصيل الشهري',
      'no_exams_assigned': 'لا توجد اختبارات',
      'no_courses_assigned': 'لا توجد دورات مسندة',
      'avg_student_progress': 'متوسط تقدم الطلاب',
      'select_months': 'اختر شهراً واحداً على الأقل',
      'income_label': 'دخل',

      // Lesson view
      'lesson_number': 'درس ',
      'video_unavailable': 'فيديو غير متاح',
      'attachments_resources': 'المرفقات والموارد',
      'unknown_file': 'ملف غير معروف',
      'play': 'تشغيل',
      'view': 'عرض',
      'download': 'تنزيل',
      'lesson_marked_completed': 'تم تعليم الدرس كمكتمل',
      'note_added': 'تمت إضافة الملاحظة',

      // Payment screen
      'order_summary': 'ملخص الطلب',
      'payment_details': 'تفاصيل الدفع',
      'transfer_info': 'معلومات التحويل:',
      'account_name': 'اسم الحساب:',
      'account_number': 'رقم الحساب:',
      'total_label': 'المجموع',
      'choose_payment_method': 'اختر طريقة الدفع',
      'submit_for_review': 'إرسال الطلب للمراجعة',
      'qr_activate_title': 'هل لديك كود تفعيل؟',
      'charge_with_qr': 'اشحن بالكود (QR)',
      'order_under_review': 'طلبك قيد المراجعة',
      'order_sent_success':
          'تم إرسال طلبك بنجاح\nسيتم مراجعته والرد عليك قريباً',
      'order_number_prefix': 'رقم الطلب: ',
      'back_to_home': 'العودة للرئيسية',
      'payment_screen_title': 'الدفع',
      'phone_from': 'رقم الهاتف الذي حولت منه',
      'transaction_number': 'رقم العملية *',
      'transaction_hint': 'أدخل رقم عملية التحويل',
      'transfer_complete_tip':
          'بعد إتمام التحويل، أدخل رقم العملية الذي حصلت عليه من التطبيق',
      'social_links_saved_success': 'تم حفظ الحسابات بنجاح!',
      'error_loading_links': 'خطأ في جلب الروابط',
      'error_saving_links': 'حدث خطأ أثناء الحفظ',
    },
    'en': {
      'cart_title': 'Shopping Cart',
      'empty_cart_msg': 'Your cart is empty',
      'browse_to_add': 'Browse courses and add them to your cart',
      'browse_courses': 'Browse Courses',
      'checkout': 'Checkout',
      'total_amount': 'Total',
      'cart_items_count': 'Items count',
      'subscribe_now_prefix': 'Subscribe now for ',
      'register_and_get': 'Register now and get',
      'unending_views': 'Unlimited views',
      'completion_certificate': 'Completion Certificate',
      'contact_coach': 'Direct contact with coach',
      'settings': 'Settings',
      'profile': 'Profile',
      'name': 'Name',
      'change_photo': 'Change Photo',
      'theme': 'Appearance',
      'display_mode': 'Display Mode',
      'light': 'Light',
      'dark': 'Dark',
      'system': 'System',
      'notifications': 'Notifications',
      'enable_notifications': 'Enable Notifications',
      'notifications_desc': 'Receive notifications for lessons and exams',
      'by_prefix': 'by',
      'video_quality': 'Video Quality',
      'about_app': 'About App',

      // Course related strings
      'start_course_now': 'Start Course Now',
      'trainer': 'Trainer',
      'course': 'Course',
      'student': 'Student',
      'about_trainer': 'About the Trainer',
      'no_bio_available': 'No bio available at the moment.',
      'no_courses_available': 'No courses available',
      'scan_qr_to_activate_course':
          'Scan QR code to activate the course immediately',
      'course_eval': 'What is your evaluation of the course?',
      'finished_all_course_lessons':
          'Well done! You have completed all lessons of the course',
      'finish_lesson_and_course': 'Complete lesson and finish course',
      'course_removed_from_favorites': 'Course removed from favorites',
      'no_favorites_yet':
          'You haven\'t added any course to favorites yet\nPress ❤️ on any course to add it here',
      'course_link_copied': 'Course link copied! You can share it now.',
      'course_enrollments': 'Course Enrollments',
      'course_enrollments_report': 'Course Enrollments Report',
      'link_to_specific_course': 'Link to a specific course (CTA)',
      'error_loading_course': 'Error loading course',
      'enter_course_desc': 'Please enter course description',
      'publish_course': 'Publish Course',
      'make_course_available': 'Make course available to students on the app',
      'choose_one_course_min': 'Please choose at least one course',
      'unknown_course': 'Unknown course',
      'course_completion_cert': 'Course completion certificate',
      'successfully_completed_course': 'Has successfully completed the course',
      'teacher_already_linked': 'Teacher is already linked to this course',
      'course_select_required': 'Please select a course',

      'version': 'Version',
      'privacy_policy': 'Privacy Policy',
      'terms_conditions': 'Terms of Service',
      'language': 'Language',
      'app_language': 'App Language',
      'educational_info': 'Educational Info',
      'professional_info': 'Professional Info',
      'education_level': 'Education Level',
      'grade': 'Grade/Year',
      'specialization': 'Specialization',
      'bio': 'Bio',
      'country': 'Country',
      'logout': 'Log Out',
      'logout_confirm_title': 'Log Out',
      'logout_confirm_desc': 'Are you sure you want to log out?',
      'cancel': 'Cancel',
      'save': 'Save',
      'edit_name': 'Edit Name',
      'enter_full_name': 'Enter full name',
      'choose_photo': 'Choose Photo',
      'camera': 'Camera',
      'gallery': 'Gallery',
      'video_quality_high': 'High',
      'video_quality_medium': 'Medium',
      'video_quality_low': 'Low',
      'error_loading': 'Error loading data',
      'changes_saved': 'Changes saved',
      'error_saving': 'Error saving changes',
      'error_image_pick': 'Error picking image',
      'error_image_upload': 'Error uploading image',
      'error_logout': 'Error logging out',
      'contact_support': 'Contact Support',
      'support_desc': 'Technical support and help',
      'delete_account': 'Delete Account',
      'delete_account_desc': 'Permanently delete your account and data',
      'delete_confirm_title': 'Delete Account',
      'delete_confirm_desc':
          'Are you sure you want to delete your account? This action cannot be undone.',
      'delete': 'Delete',
      'support_dialog_title': 'Technical Support',
      'support_dialog_desc': 'You can contact us through:',
      'email_us': 'Email Us',
      'whatsapp_us': 'WhatsApp Us',
      'home': 'Home',
      'explore': 'Explore',
      'all': 'All',
      'my_courses': 'My Courses',
      'welcome': 'Welcome, Guest',
      'guest': 'Guest',
      'searching': 'Search your next lesson...',
      'categories': 'Categories',
      'top_teachers': 'Top Teachers',
      'continue_watching': 'Continue Watching',
      'explore_more': 'Explore More',
      'search_courses': 'Search Courses',
      'search_hint': 'Search by course or teacher...',
      'filter': 'Filter',
      'filter_by_category': 'Filter by Category',
      'edit_profile': 'Edit Profile',
      'statistics': 'Statistics',
      'joined': 'Joined',
      'completed_courses': 'Completed Courses',
      'hours_spent': 'Study Hours',
      'no_courses_found': 'No courses found',
      'try_different_search': 'Try searching with different keywords',
      'featured_courses': 'Featured Courses',
      'no_featured_courses_message': 'No featured courses found at the moment.',
      'welcome_with_name': 'Welcome,',
      'lessons': 'lessons',
      'chapters': 'chapters',
      'ready_to_learn': 'Ready to learn?',
      'search_course_hint': 'Search for a course...',
      'continue_learning': 'Continue Learning',
      'completed': 'Completed',
      'featured_course_badge': 'Featured',
      'most_popular': 'Most Popular',
      'teacher': 'Teacher',
      'explore_courses': 'Explore Courses',
      'no_courses_in_category': 'No courses in this category',
      'no_categories_found': 'No categories found',
      'loading': 'Loading...',
      'current_courses': 'Current Courses',
      'completed_status': 'Completed',
      'reviews': 'reviews',
      'enrolled': 'Enrolled',
      'no_current_courses': 'No current courses',
      'no_completed_courses': 'No completed courses yet',
      'unenroll_confirm': 'Are you sure you want to unenroll?',
      'unenroll_success': 'Course removed from your list',
      'unenroll_error': 'Error during unenrollment',
      'course_removed': 'Course removed successfully',
      'no_current_courses_desc':
          'Start exploring courses and enroll in your interests!',
      'no_completed_courses_desc':
          'Once you finish a course, it will appear here in the completed list.',
      'current': 'Current',
      'admin_dashboard': 'Admin Dashboard',
      'teacher_dashboard': 'Teacher Dashboard',
      'manage_course': 'Manage Course',
      'account_upgrades': 'Account Upgrades',
      'certificates': 'Certificates',
      'learning_hours': 'Learning Hours',
      'orders': 'My Orders',
      'dashboard': 'Dashboard',
      'financial_reports': 'Financial Reports',
      'my_financial_report': 'My Financial Report',
      'all_teachers': 'All Teachers',
      'total_revenue': 'Total Revenue',
      'total_enrollments': 'Total Enrollments',
      'performance_summary': 'Performance Summary',
      'active_students': 'Active Students',
      'courses_count': 'Courses Count',
      'user': 'User',
      'completed_courses_count_label': 'Completed Course(s)',
      'no_orders_yet': 'No previous orders',
      'no_orders_desc':
          'You haven\'t purchased any courses yet. All your bills will appear here.',
      'study_continue': 'Keep studying!',
      'courses_not_completed_desc':
          'You haven\'t completed any course fully yet. Keep studying!',
      'enrolled_courses_desc':
          'Start your educational journey today and explore our available courses.',
      'no_courses_yet': 'You haven\'t purchased any course yet',
      'course_description': 'Course Description',
      'curriculum_tab': 'Curriculum',
      'reviews_tab': 'Reviews',
      'reviews_label': 'Review',
      'progress_label': 'Progress',
      'unenroll_button_label': 'Remove from list',
      'course_unavailable_label': 'Currently unavailable',
      'no_active_courses': 'No active courses',
      'start_learning_message': 'Start by adding courses from the home screen',
      'keep_learning_message': 'Keep learning to complete your courses!',
      'confirm_delete_title': 'Confirm Delete',
      'confirm_delete_message':
          'Do you want to remove this course from your list?',
      'error_label': 'Error',
      'buy_now': 'Buy Now',
      'enrolled_already': 'You are enrolled in this course',
      'pending_request': 'Your request is pending',
      'get_certificate': 'Get Certificate',
      'lesson': 'Lesson',
      'enter_course': 'Enter Course',
      'exam': 'Exam',
      'free': 'Free',
      'certificate_ready': 'Certificate is ready!',
      'premium_course': 'Premium Course',
      'no_instructor_profile': 'No instructor profile available',
      'instructor_title': 'Instructor',
      'lessons_count_label': 'Lessons',
      'reviews_count_label': 'Reviews',
      'students_count_label': 'Students',
      'duration_label': 'Hours',
      'hours_short': 'H',
      'duration': 'Duration',
      'accredited_by': 'Accredited by',
      'no_reviews_yet': 'No reviews yet',
      'add_review': 'Add your review',
      'reviewed_already': 'You have already reviewed this course',
      'be_first_to_review':
          'Be the first to review this course and share your experience',
      'anonymous_user': 'User',
      'your_comment_here': 'Write your comment here...',
      'publish': 'Publish',
      'adding_review': 'Adding review...',
      'review_added_success': 'Your review has been added successfully',
      'no_lessons_yet': 'No lessons yet',
      'read_more': 'Read More',
      'read_less': 'Read Less',
      'similar_courses': 'Similar Courses',
      'view_all_reviews': 'Show all reviews and opinions',
      'course_content_working': 'Content is being added to this course soon.',
      'other_lessons': 'Other Lessons',
      'course_content': 'Course Content',
      'must_complete_previous': 'You must complete the previous lesson first',
      'description_tab': 'Description',
      'attachments_tab': 'Attachments',
      'interactive_tab': 'Interactive',
      'exams_tab': 'Exams',
      'notes_tab': 'Notes',
      'questions_tab': 'Questions',
      'lesson_prefix': 'Lesson',
      'delete_note': 'Delete Note',
      'delete_note_confirm': 'Are you sure you want to delete this note?',
      'note_deleted_success': 'Note deleted successfully',
      'edit_note': 'Edit Note',
      'no_video_available': 'No video available for this lesson',
      'no_interactive_content': 'No interactive content for this lesson',
      'recent_exam_attempts': 'Recent Student Attempts',
      'no_recent_attempts': 'No recent attempts',
      'must_subscribe': 'You must subscribe to the course to watch this lesson',
      'no_exam_at_all': 'No exam for this lesson. Moving to next...',
      'must_take_exam': 'You must pass the exam for this lesson first',
      'start_exam': 'Start Exam',
      'ai_assistant': 'AI Assistant',
      'ai_assistant_coming_soon':
          'AI features will be available in a future update',
      'ai_features_notice':
          'We are working on integrating AI technologies to enhance your learning experience.',
      'view_details': 'View Details',
      'order_report': 'Order Report',
      'details': 'Details',
      'transaction_id': 'Transaction ID',
      'payment_method': 'Payment Method',
      'phone_number': 'Phone Number',
      'order_date': 'Order Date',
      'status': 'Status',
      'order_number': 'Order Number',
      'app_updates': 'App Updates',
      'all_categories': 'All Categories',
      'category_label': 'Category',
      'manage_app_updates': 'Manage App Updates',
      'version_name': 'Version Name',
      'download_url': 'Download URL',
      'release_notes': 'Release Notes',
      'is_mandatory_label': 'Mandatory Update',
      'add_update': 'Add New Update',
      'update_success': 'Update added successfully',
      'mandatory': 'Mandatory',
      'optional': 'Optional',
      'show_all': 'Show All',
      'discount_percentage': 'Discount Percentage (%)',
      'enter_discount': 'Enter discount percentage',
      'discount_range_error': 'Percentage must be between 0 and 100',
      'manage_my_courses': 'Manage My Courses',
      'manage_courses': 'Manage Courses',
      'courses_count_title': 'Courses',
      'total_courses_count': 'Total {count} Courses',
      'general_specialization': 'General Specialization',
      'categories_title': 'Categories',
      'search': 'Search',
      'published': 'Published',
      'draft': 'Draft',
      'type_label': 'Ad Type',
      'performance_summary_title': 'Performance and Growth Summary',
      'total_attempts_title': 'Total Attempts',
      'active_users_label': 'Active (Weekly)',
      'weekly_growth_label': 'Weekly Growth',
      'total_revenue_label': 'Total Revenue',
      'student_label': 'Students',
      'course_unit_label': 'Courses',
      'attempt_unit_label': 'Attempts',
      'level_label': 'Level',
      'recorded': 'Recorded',
      'live': 'Live',
      'in_person': 'In-person',
      'unspecified_teacher': 'Unspecified Teacher',
      'current_teachers': 'Current Teachers',
      'pending_requests': 'Pending Requests',
      'teachers_management_title': 'Teacher Management',
      'exams': 'Exams',
      'edit': 'Edit',
      'no_courses_current': 'No courses found',
      'start_adding_first_course':
          'Start by adding the first educational course',
      'delete_course_title': 'Delete Course',
      'delete_course_confirm':
          'Are you sure you want to delete this course? All associated lessons will be deleted.',
      'close': 'Close',
      'subscribers': 'Subscribers',
      'completers': 'Completers',
      'average_progress_label': 'Average Progress',
      'completion_rate_label': 'Completion Rate',
      'course_outcomes': 'Course Outcomes',
      'target_audience': 'Target Audience',
      'own_this_course': 'Own this course for',
      'course_register_and_get': 'Register for this course and get',
      'course_unending_views': 'Unlimited views',
      'course_contact_coach': 'Contact with coach',
      'course_completion_certificate': 'Course completion certificate',
      'or': 'Or',
      'course_subscribe_now_prefix': 'Enroll Now - ',
      'all_levels': 'All Levels',
      'beginner': 'Beginner',
      'intermediate': 'Intermediate',
      'advanced': 'Advanced',
      'expert': 'Expert',
      'decision_making': 'Decision Making',
      'goal_achievement': 'Goal Achievement',
      'self_development': 'Self Development',
      'order_priorities': 'Prioritize',
      'body_language': 'Body Language',
      'edit_course': 'Edit Course',
      'create_new_course': 'Create New Course',
      'select_teacher': 'Select Responsible Teacher',
      'search_teacher': 'Search for teacher...',
      'pricing_time_data': 'Pricing & Time Details',
      'free_course': 'Free Course',
      'free_course_desc': 'All students will be able to access it for free',
      'price': 'Price',
      'price_hint': '0 for free',
      'currency': 'Currency',
      'instructor_and_visibility': 'Instructor & Visibility',
      'unspecified': 'Unspecified',
      'is_published_label': 'Status: Published',
      'subject_label': 'Subject',
      'subject_hint': 'Example: Physics',
      'error_enter_subject': 'Please enter the subject name',
      'tags_optional_label': 'Tags (Optional):',
      'basic_info_label': 'Basic Information',
      'course_image_url': 'Course Image URL',
      'image_url_hint': 'https://example.com/image.jpg',
      'video_url_label': 'Promotional Video URL',
      'video_url_hint': 'https://vimeo.com/... or direct link',
      'course_title_label': 'Course Title',
      'course_title_hint': 'Example: Advanced Math Course',
      'error_enter_title': 'Please enter the course title',
      'course_description_hint': 'Detailed description of the course content',
      'error_enter_description': 'Please enter the course description',
      'course_category_label': 'Course Category',
      'select_category_label': 'Select Category',
      'welcome_to_doraty': 'Welcome to Doraty Platform',
      'select_account_type': 'Please select your account type to continue',
      'join_as_student': 'Join as Student',
      'student_desc': 'Browse courses and learn new skills',
      'join_as_teacher': 'Join as Teacher',
      'teacher_desc': 'Publish your courses and start teaching',
      'first_name_label': 'First Name',
      'last_name_label': 'Last Name',
      'username_label': 'Username',
      'email_label': 'Email',
      'password_label': 'Password',
      'confirm_password_label': 'Confirm Password',
      'terms_accept_label': 'I agree to the Terms and Conditions',
      'personal_info': 'Personal Information',
      'educational_info_header': 'Educational Information',
      'security_header': 'Security',
      'required_suffix': '(Required)',
      'invalid_email': 'Invalid Email',
      'pass_min_char': 'At least 6 characters',
      'pass_dont_match': 'Passwords do not match',
      'grade_level_label': 'Grade Level',
      'university_specialization_label': 'University Specialization',
      'academic_year_label': 'Academic Year',
      'required_field': 'Required',
      'register_new_coach': 'Register New Coach',
      'participation_plans': 'Participation Plans',
      'participation_intent_label':
          'I want to join the platform for (Required):',
      'phone_number_label': 'Phone Number',
      'country_label': 'Country',
      'specialization_label': 'Specialization',
      'give_full_courses_label': 'Give Full Courses',
      'teach_private_hours_label': 'Teach Private Tutoring',
      'cv_label': 'CV / Resume',
      'certificates_label': 'Academic Certificates',
      'short_bio_hint': 'Brief bio about yourself',
      'success_submit_teacher':
          'Your application has been submitted successfully! We will review it and get back to you soon.',
      'select_sub_type_error':
          'Please select a subscription type (Courses or Tutoring)',
      'fail_get_user_id': 'Failed to get user ID',
      'no_file_selected': 'No file selected (Max 5MB)',
      'change': 'Change',
      'choose': 'Choose',
      'submit_request': 'Submit Request',
      'create_account': 'Create Account',
      'school': 'School',
      'university': 'University',
      'save_changes': 'Save Changes',
      'course_created_success': 'Course created successfully',
      'course_updated_success': 'Course updated successfully',
      'error_saving_data': 'Error saving data',
      'select_at_least_one_category': 'Please select at least one category',
      'error_select_teacher': 'Please select an instructor',
      'error_select_level': 'Please select a course level',
      'error_select_category': 'Please select at least one category',
      'register_title': 'Register New Account',
      'register_subtitle': 'Join us and start your learning journey',
      'student_role': 'Student',
      'teacher_role': 'Teacher',
      'register_action': 'Create Account',
      'already_have_account': 'Already have an account?',
      'login_now': 'Login Now',
      'or_via': 'Or via',
      'account_created_success': 'Account created successfully! Welcome',
      'bundle_badge': 'Bundle',
      'courses_count_bundle': 'Courses',
      'all_bundles': 'All Bundles',
      'bundle_details': 'Bundle Details',
      'included_courses': 'Included Courses',
      'buy_bundle': 'Buy Bundle',
      'featured_bundles': 'Featured Bundles',
      'login_title': 'Login',
      'login_required_title': 'Login Required',
      'login_required_desc':
          'Please login to access your profile and track your courses',
      'offline_mode': 'Offline Mode (Cached Data)',
      'ad_banner_title': 'Premium Study Plans',
      'ad_banner_subtitle': 'Subscribe to a bundle and save over 50%',
      'view_plans_button': 'View Plans',
      'new_courses': 'Newest Courses',
      'most_watched': 'Most Watched',
      'recorded_courses': 'Uploaded Courses',
      'learning_tips_title': 'Learning Tips',
      'tips': 'Tips',
      'bundles_title': 'Special Bundles',
      'hello': 'Welcome',
      'my_receipts': 'My Receipts',
      'favorites': 'Favorites',
      'faq': 'FAQ',
      'faq_search_hint': 'Search for a question...',
      'faq_how_subscribe': 'How can I subscribe to a course?',
      'faq_how_subscribe_ans':
          'Choose the course you want, then click the "Enroll" button and complete the payment process.',
      'faq_payment_methods': 'What are the available payment methods?',
      'faq_payment_methods_ans':
          'Currently, we support bank transfers and cash at our centers. Electronic payments will be added soon.',
      'faq_certificate': 'Do I get a certificate after completing the course?',
      'faq_certificate_ans':
          'Yes, you will receive an electronic certificate immediately after completing all course lessons and tests.',
      'faq_contact_teacher': 'How can I contact the instructor?',
      'faq_contact_teacher_ans':
          'You can ask your questions via the comments section or direct messages with the instructor.',
      'faq_support': 'How do I contact technical support?',
      'faq_support_ans':
          'You can contact us through the "Contact Support" page in the side drawer.',
      'dark_mode_title': 'Dark Mode',
      'banners_management': 'Banners Management',
      'no_banners_found': 'No banners found',
      'add_banner': 'Add New Banner',
      // Admin Dashboard
      'admin_users': 'Users',
      'admin_users_desc': 'Manage all platform users',
      'admin_categories': 'Categories',
      'admin_categories_desc': 'Manage course categories',
      'admin_teachers': 'Teachers Affairs',
      'admin_teachers_desc': 'Manage instructors and joining requests',
      'admin_bundles': 'Bundles',
      'admin_bundles_desc': 'Manage course bundles',
      'admin_tips_side': 'Tips',
      'admin_tips_desc': 'Manage short video tips',
      'admin_banners_side': 'Banners',
      'admin_banners_desc': 'Manage animated banner images',
      'admin_courses_desc': 'Manage course content',
      'course_lessons': 'Course Lessons',
      'add_lesson': 'Add Lesson',
      'minutes_unit': 'min(s)',
      'exams_label': 'Exams:',
      'add_exam': 'Add Exam',
      'order_updated': 'Order Updated',
      'delete_lesson_confirm': 'Are you sure you want to delete this lesson?',
      'edit_chapter': 'Edit Chapter',
      'no_chapters_yet': 'No chapters yet',
      'manage_chapters': 'Manage Chapters',
      'delete_lesson': 'Delete Lesson',
      'lesson_removed': 'Lesson Removed',
      'delete_chapter': 'Delete Chapter',
      'delete_chapter_confirm':
          'Are you sure? Lessons will remain but without a chapter.',
      'add_chapter': 'Add Chapter',
      'add_new': 'Add New',
      'no_lessons': 'No Lessons',
      'start_adding_first_lesson': 'Start by adding your first lesson',
      'search_users_hint': 'Search for user...',
      'admin_role_label': 'Admin',
      'teacher_role_label': 'Teacher',
      'student_role_label': 'Student',
      'assign_role': 'Assign Role',
      'cannot_edit_admin_roles': 'Cannot edit admin roles',
      'role_assigned_success': 'Role assigned successfully',
      'admin_subscriptions_side': 'Subscriptions',
      'admin_subscriptions_desc': 'Monitor student subscriptions',
      'admin_payments_side': 'Payments',
      'admin_payments_desc': 'Review payment receipts',
      'admin_payment_settings_side': 'Payment Settings',
      'admin_payment_settings_desc': 'Edit payment accounts',
      'admin_financial_reports': 'Financial Reports',
      'admin_financial_reports_desc': 'Export revenue reports',
      'admin_notifications_side': 'Notifications',
      'admin_notifications_desc': 'Send general notifications',
      'admin_qr_side': 'QR Codes',
      'admin_qr_desc': 'Generate activation codes',
      'admin_updates_side': 'App Updates',
      'admin_updates_desc': 'Release new versions',
      'admin_security_side': 'Security Settings',
      'admin_security_desc': 'Control screenshots',
      'admin_quick_actions': 'Quick Actions',
      'admin_recent_attempts': 'Recent Student Attempts',
      'admin_no_attempts': 'No recent attempts in system logs',
      'admin_view_all': 'View All',
      'admin_student': 'Student',
      'admin_unknown_exam': 'Unknown Exam',
      'admin_passed': 'Passed',
      'admin_failed': 'Failed',
      'title': 'Title',
      'financial_report': 'Financial Report',
      'platform_name': 'Doraty Educational Platform',
      'period': 'Period',
      'print_date': 'Print Date',
      'enrollments_count': 'Enrollments Count',
      'date': 'Date',
      'amount': 'Amount',
      'select_period': 'Select Period',
      'filter_by_course_optional': 'Filter by Course (Optional)',
      'generate_report': 'Generate Report',
      'tips_management': 'Tips Management',
      'delete_tip': 'Delete Tip',
      'delete_tip_confirm': 'Are you sure you want to delete this tip?',
      'tip_deleted_success': 'Tip deleted successfully',
      'no_tips_found': 'No tips found at the moment',
      'add_first_tip': 'Add first tip',
      'views_unit': 'view(s)',
      'linked_to_course': 'Linked to course',
      'new_tip': 'New Tip',
      'error_delete_tip': 'Error deleting tip',
      'bundles_management': 'Bundles Management',
      'no_bundles_found_admin': 'No bundles found currently',
      'add_new_bundle': 'Add New Bundle',
      'delete_bundle_confirm': 'Are you sure you want to delete this bundle?',
      'currency_syp': 'SYP',
      'yes': 'Yes',
      'no': 'No',
      'categories_management': 'Categories Management',
      'add_category': 'Add Category',
      'base_category': 'Base Category',
      'sub_categories': 'Sub-categories',
      'no_sub_categories': 'No sub-categories',
      'edit_category': 'Edit Category',
      'add_new_category': 'Add New Category',
      'category_name': 'Category Name',
      'slug_label': 'Identifier (Slug)',
      'icon_url_optional': 'Icon URL (Optional)',
      'parent_category_optional': 'Parent Category (Optional)',
      'main_category': 'Main Category',
      'none_main_category': 'None (Main Category)',
      'please_fill_required_fields': 'Please fill required fields',
      'delete_category_confirm':
          'Are you sure you want to delete this category?',
      'banners_management_title': 'Banners & Ads Management',
      'no_banners_found_admin': 'No ads currently',
      'add_new_banner': 'Add New Ad',
      'edit_banner': 'Edit Ad',
      'ad_preview': 'Ad Preview',
      'main_title': 'Main Title',
      'subtitle_action_text_optional': 'Subtitle / Action Text (Optional)',
      'image_url_label': 'Image URL',
      'image_upload_success': 'Image uploaded successfully',
      'error_upload_image': 'Error uploading image',
      'ad_type': 'Ad Type',
      'general_ad': 'General Ad',
      'specific_course': 'Specific Course',
      'bundle_offer': 'Bundle / Offer',
      'external_link': 'External Link',
      'select_course': 'Select Course',
      'select_bundle': 'Select Bundle',
      'display_location': 'Display Location',
      'main_top': 'Main (Top)',
      'secondary_bottom': 'Secondary (Bottom)',
      'visit_link': 'Visit Link',
      'ad_title_fallback': 'Ad Title',
      'click_to_select': 'Click to select...',
      'id_label': 'ID',
      'delete_banner_confirm': 'Are you sure you want to delete this ad?',
      'search_hint_name_teacher': 'Search by name or teacher...',
      'no_results': 'No results found',
      'location_label': 'Location',
      'top_location': 'Top',
      'bottom_location': 'Bottom',
      'no_teachers_found': 'No teachers found at the moment',
      'no_pending_requests': 'No pending joining requests',
      'new_request': 'New Request',
      'approve': 'Approve',
      'reject': 'Reject',
      'request_approved_success': 'Request approved successfully',
      'request_rejected_success': 'Request rejected successfully',
      'no_email': 'No email provided',
      'manage_courses_btn': 'Manage Courses',
      'create_exam': 'Create Exam',
      'manage_exams': 'Manage Exams',
      'unpublish': 'Unpublish',
      'manage_questions': 'Manage Questions',
      'no_exams_found': 'No exams found',
      'create_exam_prompt': 'Start by creating a new exam for this course',
      'unpublish_success': 'Unpublished successfully',
      'publish_success': 'Published successfully',
      'delete_exam_title': 'Delete Exam',
      'delete_exam_confirm': 'Are you sure you want to delete this exam?',
      'delete_exam_success': 'Exam deleted successfully',
      'notifications_management': 'Notifications Management',
      'send_new_notification': 'Send New Notification',
      'notification_history': 'Sent Notifications History',
      'send_to': 'Send To',
      'all_users': 'All Users',
      'specific_course_students': 'Specific Course Students',
      'specific_user': 'Specific User',
      'select_target_error': 'Please select target (course or user)',
      'notification_sent_success': 'Sent successfully to {count} users',
      'notification_send_failed': 'Failed to send',
      'no_notification_history': 'No notification history found',
      'notification_title': 'Notification Title',
      'notification_body': 'Notification Body',
      'send_notification_btn': 'Send Notification',
      'manage_subscriptions': 'Manage Subscriptions',
      'print_report': 'Print Report',
      'revenue': 'Revenue',
      'total_students': 'Total Students',
      'search_subscription_hint': 'Search by student name or course...',
      'filter_by_date_all': 'Filter by date: All',
      'filter_prefix': 'Filter: ',
      'year_prefix': 'Year ',
      'by_course': 'By Course',
      'by_teacher': 'By Teacher',
      'unassigned_course': 'Unassigned Course',
      'subscription_date': 'Subscription Date',
      'cancel_subscription': 'Cancel Subscription',
      'no_matching_subscriptions': 'No matching subscriptions',
      'confirm_cancellation': 'Confirm Cancellation',
      'cancel_subscription_confirm':
          'Are you sure you want to change the subscription status for this student? This will revoke their access to the content.',
      'subscription_updated_success':
          'Subscription status updated successfully',
      'select_filter_period': 'Select Filter Period',
      'monthly': 'Monthly',
      'yearly': 'Yearly',
      'financial_report_title': 'Financial Report',
      'period_prefix': 'Period: ',
      'print_date_prefix': 'Print Date: ',
      'fail_generate_report': 'Failed to generate report: ',
      'print_all_confirm_desc':
          'No filter period selected (month or year). A report for all subscriptions will be printed. Do you want to continue?',
      'continue_action': 'Continue',
      'cash': 'Cash',
      'detailed_management': 'Detailed Management',
      'teacher_stats': 'Teacher Stats',
      'course_count_prefix': 'Course Count: ',
      'welcome_text': 'Welcome',
      'forgot_password': 'Forgot Password?',
      'dont_have_account': 'Don\'t have an account?',
      'register_now': 'Register Now',
      'reset_password': 'Reset Password',
      'reset_password_desc':
          'Enter your email and we will send you a link to reset your password.',
      'admin_social_links_side': 'Social Links',
      'admin_social_links_desc': 'Manage social media accounts',
      'social_facebook': 'Facebook',
      'social_instagram': 'Instagram',
      'social_youtube': 'YouTube',
      'social_whatsapp': 'WhatsApp',
      'social_x_twitter': 'X (Twitter)',
      'social_linkedin': 'LinkedIn',
      'social_tiktok': 'TikTok',
      'social_telegram': 'Telegram',
      'social_url_hint': 'Enter URL here. Leave empty to hide',
      'error_enter_email': 'Please enter your email',
      'error_enter_password': 'Please enter your password',
      'reset_password_success':
          'Password reset link has been sent to your email.',
      'send': 'Send',
      'checking_account': 'Checking account...',
      'login_canceled': 'Google login canceled',
      'cart_content': 'Basket Content',
      'discount': 'Discount',
      'subtotal': 'Subtotal',
      'add_discount_code': 'Add Discount Code',
      'complete_registration': 'Complete Registration',
      'course_not_found': 'Sorry, the course was not found',
      'upcoming_exams': 'Upcoming Exams',
      'no_upcoming_exams': 'No upcoming exams',
      'completed_exams': 'Completed Exams',
      'no_completed_exams': 'No completed exams',
      'points': 'Points',
      'subject_math': 'Mathematics',
      'subject_physics': 'Physics',
      'subject_chemistry': 'Chemistry',
      'subject_biology': 'Biology',
      'subject_arabic': 'Arabic Language',
      'subject_english': 'English Language',
      'subject_french': 'French Language',
      'subject_religion': 'Religion',
      'subject_history': 'History',
      'subject_geography': 'Geography',
      'subject_philosophy': 'Philosophy',
      'subject_sociology': 'Sociology',
      'high_school_courses_desc': 'High School {subject} Courses',
      'exam_math_title': 'Chapter One Exam - Mathematics',
      'exam_math_desc':
          'Comprehensive Chapter One exam covering quadratic equations and calculus',
      'exam_math_course': 'Advanced Mathematics',
      'exam_physics_title': 'Physics Exam - Motion',
      'exam_physics_desc': 'Exam on laws of motion, velocity, and acceleration',
      'exam_physics_course': 'Physics',
      'exam_chemistry_title': 'Chemistry Exam - Periodic Table',
      'exam_chemistry_desc': 'Exam on periodic table elements and properties',
      'exam_chemistry_course': 'Chemistry',
      'student_results': 'student results ',

      // Exams management
      'exams_management': 'Exams Management',
      'minute': 'Min',
      'no_exams': 'No Exams Found',
      'confirm_delete_exam': 'Are you sure you want to delete this exam?',

      // Teacher dashboard
      'teacher_dashboard_welcome': 'Welcome to your dashboard',
      'total_income': 'Total Income',
      'total_students_stat': 'Total Students',
      'courses_stat': 'Courses',
      'exams_stat': 'Exams',
      'quick_actions': 'Quick Actions',
      'recent_exams': 'Recent Exams',
      'teacher_stats_report': 'Teacher Statistics Report',
      'period_label': 'Period: ',
      'date_label': 'Date: ',
      'income_stat': 'Total Income',
      'enrollments_stat': 'Enrollments',
      'attempts_stat': 'Attempts',
      'monthly_breakdown': 'Monthly Breakdown',
      'no_exams_assigned': 'No exams assigned',
      'no_courses_assigned': 'No courses assigned',
      'avg_student_progress': 'Average Student Progress',
      'select_months': 'Please select at least one month',
      'income_label': 'Income',

      // Lesson view
      'lesson_number': 'Lesson ',
      'video_unavailable': 'Video not available',
      'attachments_resources': 'Attachments & Resources',
      'unknown_file': 'Unknown file',
      'play': 'Play',
      'view': 'View',
      'download': 'Download',
      'lesson_marked_completed': 'Lesson marked as completed',
      'note_added': 'Note added successfully',

      // Payment screen
      'order_summary': 'Order Summary',
      'payment_details': 'Payment Details',
      'transfer_info': 'Transfer Information:',
      'account_name': 'Account Name:',
      'account_number': 'Account Number:',
      'total_label': 'Total',
      'choose_payment_method': 'Choose Payment Method',
      'submit_for_review': 'Submit for Review',
      'qr_activate_title': 'Have an activation code?',
      'charge_with_qr': 'Charge with Code (QR)',
      'order_under_review': 'Your order is under review',
      'order_sent_success':
          'Your request has been sent successfully\nIt will be reviewed and you will be notified soon',
      'order_number_prefix': 'Order Number: ',
      'back_to_home': 'Back to Home',
      'payment_screen_title': 'Payment',
      'phone_from': 'Phone number you transferred from',
      'transaction_number': 'Transaction Number *',
      'transaction_hint': 'Enter the transfer transaction number',
      'transfer_complete_tip':
          'After completing the transfer, enter the transaction number you received from the app',
      'bundles_label': 'Related Packages',
      'no_bundles_available': 'No packages available at the moment',
      'social_links_saved_success': 'Social links saved successfully!',
      'error_loading_links': 'Error loading social links',
      'error_saving_links': 'Error saving social links',
      'no_sessions_yet': 'No scheduled sessions yet',
      'live_sessions': 'Live Sessions',
      'watch_recording': 'Watch Recording',
      'join': 'Join Now',
      'sessions_tab': 'Sessions & Schedule',
      'location': 'Location',
      'recorded_desc': 'Full recorded course you can start anytime',
      'live_desc': 'Interactive live sessions with the instructor',
      'in_person_desc': 'In-person training at the center',
    },
  };

  static String get(String key, String lang) {
    return _localizedValues[lang]?[key] ?? _localizedValues['ar']?[key] ?? key;
  }
}
