class AppStrings {
  static const Map<String, Map<String, String>> _localizedValues = {
    'ar': {
      'settings': 'الإعدادات',
      'profile': 'الملف الشخصي',
      'name': 'الاسم',
      'change_photo': 'تغيير الصورة',
      'theme': 'المظهر',
      'display_mode': 'وضع العرض',
      'light': 'فاتح',
      'dark': 'داكن',
      'system': 'تلقائي',
      'notifications': 'الإشعارات',
      'enable_notifications': 'تفعيل الإشعارات',
      'notifications_desc': 'استقبال إشعارات الدروس والاختبارات',
      'downloads': 'التحميل',
      'auto_download': 'التحميل التلقائي',
      'auto_download_desc': 'تحميل الدروس تلقائياً عند الاتصال بالواي فاي',
      'wifi_only': 'التحميل عبر واي فاي فقط',
      'wifi_only_desc': 'توفير استهلاك البيانات عبر شبكة الجوال',
      'video_quality': 'جودة الفيديو',
      'clear_downloads': 'مسح التنزيلات',
      'clear_downloads_desc': 'حذف جميع الدروس المحملة لتوفير المساحة',
      'about': 'حول الكورس ',
      'version': 'الإصدار',
      'privacy_policy': 'سياسة الخصوصية',
      'terms_conditions': 'شروط الاستخدام',
      'language': 'اللغة',
      'app_language': 'لغة التطبيق',
      'logout': 'تسجيل الخروج',
      'logout_confirm_title': 'تسجيل الخروج',
      'logout_confirm_desc': 'هل أنت متأكد من تسجيل الخروج؟',
      'cancel': 'إلغاء',
      'save': 'حفظ',
      'edit_name': 'تعديل الاسم',
      'enter_full_name': 'أدخل الاسم الكامل',
      'choose_photo': 'اختيار الصورة',
      'camera': 'الكاميرا',
      'gallery': 'معرض الصور',
      'video_quality_high': 'عالية',
      'video_quality_medium': 'متوسطة',
      'video_quality_low': 'منخفضة',
      'clear_downloads_confirm_title': 'مسح التنزيلات',
      'clear_downloads_confirm_desc': 'هل أنت متأكد من مسح جميع الدروس المحملة؟',
      'clear': 'مسح',
      'clearing': 'جاري مسح التنزيلات...',
      'clear_success': 'تم مسح جميع التنزيلات بنجاح',
      'error_loading': 'خطأ في تحميل البيانات',
      'changes_saved': 'تم حفظ التغييرات',
      'error_saving': 'خطأ في حفظ التغييرات',
      'error_image_pick': 'خطأ في اختيار الصورة',
      'error_image_upload': 'خطأ في رفع الصورة',
      'error_logout': 'خطأ في تسجيل الخروج',
      'contact_support': 'تواصل مع الدعم',
      'support_desc': 'الدعم الفني والمساعدة',
      'delete_account': 'حذف الحساب',
      'delete_account_desc': 'حذف حسابك وجميع بياناتك نهائياً',
      'delete_confirm_title': 'حذف الحساب',
      'delete_confirm_desc': 'هل أنت متأكد من رغبتك في حذف حسابك؟ هذا الإجراء لا يمكن التراجع عنه.',
      'delete': 'حذف',
      'support_dialog_title': 'الدعم الفني',
      'support_dialog_desc': 'يمكنك التواصل معنا عبر الوسائل التالية:',
      'email_us': 'راسلنا عبر البريد الإلكتروني',
      'whatsapp_us': 'تواصل معنا عبر واتساب',
      'home': 'الرئيسية',
      'explore': 'تصفح',
      'my_courses': 'دوراتي',
      'welcome': 'أهلاً بك يا ضيف',
      'guest': 'ضيف',
      'searching': 'ابحث عن درسك التالي...',
      'categories': 'التصنيفات',
      'all': 'الكل',
      'top_teachers': 'أفضل المعلمين',
      'continue_watching': 'متابعة المشاهدة',
      'explore_more': 'تصفح المزيد',
      'search_courses': 'البحث عن الدورات',
      'search_hint': 'ابحث باسم الدورة أو المعلم...',
      'filter': 'تصفية',
      'filter_by_category': 'تصفية حسب التصنيف',
      'my_downloads': 'تنزيلاتي',
      'edit_profile': 'تعديل الملف الشخصي',
      'statistics': 'الإحصائيات',
      'joined': 'انضم في',
      'completed_courses': 'الدورات المكتملة',
      'hours_spent': 'ساعات الدراسة',
      'no_courses_found': 'لم يتم العثور على دورات',
      'try_different_search': 'حاول البحث بكلمات مختلفة',
      'featured_courses': 'دورات مميزة',
      'no_featured_courses_message': 'لم يتم العثور على أي دورات مميزة في الوقت الحالي.',
      'welcome_with_name': 'أهلاً بك يا',

      'ready_to_learn': 'جاهز للتعلم؟',
      'search_course_hint': 'ابحث عن دورة...',
      'continue_learning': 'تابع التعلم',
      'completed': 'اكتمل',
      'featured_course_badge': 'دورة مميزة',
      'most_popular': 'الأكثر طلباً',
      'teacher': 'مدرس',
      'explore_courses': 'استكشف الدورات',
      'no_courses_in_category': 'لا توجد دورات في هذا القسم',
      'no_categories_found': 'لم يتم العثور على تصنيفات',
      'loading': 'جاري التحميل...',
      'current_courses': 'دوراتي الحالية',
      'completed_status': 'مكتملة',
      'enrolled': 'مسجل',
      'no_current_courses': 'لا توجد دورات حالية',
      'no_completed_courses': 'لا توجد دورات مكتملة بعد',
      'unenroll_confirm': 'هل أنت متأكد من إلغاء التسجيل؟',
      'unenroll_success': 'تم إزالة الدورة من قائمتك',
      'unenroll_error': 'حدث خطأ أثناء إلغاء التسجيل',
      'course_removed': 'تم إزالة الدورة بنجاح',
      'no_current_courses_desc': 'ابدأ بتصفح الدورات وسجل في اهتماماتك!',
      'no_completed_courses_desc': 'بمجرد إنهاء الدورة، ستظهر هنا في قائمة المكتملة.',
      'current': 'الحالية',
      'admin_dashboard': 'لوحة تحكم المشرف',
      'teacher_dashboard': 'لوحة تحكم الأستاذ',
      'account_upgrades': 'ترقيات الحساب',
      'certificates': 'شهادات',
      'learning_hours': 'ساعة تعلم',
      'orders': 'طلباتي',
      'dashboard': 'لوحة التحكم',
      'user': 'المستخدم',
      'completed_courses_count_label': 'دورة مكتملة',
      'no_orders_yet': 'لا توجد طلبات سابقة',
      'no_orders_desc': 'لم تقم بشراء أي دورات بعد. جميع فواتيرك ستظهر هنا.',
      'study_continue': 'استمر في الدراسة!',
      'courses_not_completed_desc': 'لم تكمل أي دورة بالكامل حتى الآن. استمر في الدراسة!',
      'enrolled_courses_desc': 'ابدأ رحلتك التعليمية اليوم واستكشف دوراتنا المتاحة.',
      'no_courses_yet': 'لم تشتر أي دورة بعد',
      'course_description': 'وصف الدورة',
      'curriculum_tab': 'المنهاج',
      'reviews_tab': 'التقييمات',
      'buy_now': 'اشترِ الآن',
      'enrolled_already': 'أنت مسجل في هذه الدورة',
      'pending_request': 'طلبك قيد المراجعة',
      'download_course': 'تنزيل الدورة',
      'get_certificate': 'الحصول على الشهادة',
      'lesson': 'درس',
      'lessons': 'دروس',
      'exam': 'اختبار',
      'free': 'مجاني',
      'certificate_ready': 'الشهادة جاهزة!',
      'premium_course': 'دورة مميزة',
      'no_instructor_profile': 'لا يوجد ملف شخصي لهذا المدرب حالياً',
      'instructor_title': 'الأستاذ',
      'reviews_count_label': 'تقييم',
      'reviews_label': 'تقييم',
      'progress_label': 'التقدم',
      'offline_badge_label': 'محمّل على الجهاز',
      'unenroll_button_label': 'حذف من قائمتي',
      'course_unavailable_label': 'هذه الدورة غير متاحة حالياً',
      'no_active_courses': 'لا توجد دورات حالية',
      'start_learning_message': 'ابدأ بإضافة دورات من الصفحة الرئيسية',
      'keep_learning_message': 'استمر في التعلم لإكمال دوراتك!',
      'confirm_delete_title': 'تأكيد الحذف',
      'confirm_delete_message': 'هل تريد إزالة هذه الدورة من قائمتك؟',
      'error_label': 'خطأ',
      'lessons_count_label': 'درس',
      'students_count_label': 'طالب',
      'duration_label': 'ساعة',
      'no_reviews_yet': 'لا توجد تقييمات بعد',
      'reviews': 'تقييمات',
      'add_review': 'أضف تقييمك',
      'your_comment_here': 'اكتب تعليقك هنا...',
      'publish': 'نشر',
      'adding_review': 'جاري إضافة التقييم...',
      'review_added_success': 'تم إضافة تقييمك بنجاح',
      'no_lessons_yet': 'لا توجد دروس حالياً',
      'course_content_working': 'يتم العمل على إضافة محتوى لهذه الدورة قريباً.',
      'other_lessons': 'دروس أخرى',
      'course_content': 'محتوى الدورة',
      'must_complete_previous': 'يجب إكمال الدرس السابق أولاً',
      'description_tab': 'الوصف',
      'attachments_tab': 'المرفقات',
      'interactive_tab': 'تفاعل',
      'exams_tab': 'اختبارات',
      'notes_tab': 'الملاحظات',
      'questions_tab': 'الأسئلة',
      'lesson_prefix': 'الدرس',
      'starting_download': 'جاري تجهيز الملف...',
      'download_success_encrypted': 'تم تجهيز الملف بنجاح',
      'download_error': 'خطأ في التحميل',
      'delete_note': 'حذف الملاحظة',
      'delete_note_confirm': 'هل أنت متأكد من رغبتك في حذف هذه الملاحظة؟',
      'note_deleted_success': 'تم حذف الملاحظة بنجاح',
      'edit_note': 'تعديل الملاحظة',
      'no_video_available': 'لا يوجد فيديو لهذا الدرس',
      'no_interactive_content': 'لا يوجد محتوى تفاعلي مخصص لهذا الدرس',
      'flashcards_tab': 'بطاقات الاستذكار',
      'generate_flashcards': 'إنشاء بطاقات ذكية بالذكاء الاصطناعي',
      'review_flashcards': 'مراجعة البطاقات التعليمية',
      'flashcards_desc':
          'بطاقات استذكار ذكية تعتمد على محتوى الدرس لمساعدتك في الحفظ والمراجعة باستخدام نظام التكرار المتباعد.',
      'generating_flashcards':
          'جاري إنشاء البطاقات باستخدام الذكاء الاصطناعي...',
      'flashcards_generated_success':
          'تم إنشاء البطاقات بنجاح! يمكنك الآن البدء في المراجعة.',
      'recent_exam_attempts': 'أحدث محاولات الطلاب',
      'no_recent_attempts': 'لا توجد محاولات حديثة',
      'must_subscribe': 'يجب الاشتراك في المادة لمشاهدة هذا الدرس',
      'no_exam_at_all': 'لا يوجد اختبار لهذا الدرس. الانتقال للدرس التالي...',
      'must_take_exam': 'يجب اجتياز اختبار هذا الدرس أولاً',
      'start_exam': 'بدء الاختبار',
      'discussions': 'المناقشات',
      'discussions_coming_soon': 'ستتاح الميزة في تحديث قادم',
      'ai_assistant': 'المساعد الذكي',
      'ai_assistant_coming_soon': 'ستتاح ميزة الذكاء الاصطناعي في تحديث قادم',
      'ai_features_notice':
          'نحن نعمل على دمج تقنيات الذكاء الاصطناعي لتعزيز تجربتك التعليمية.',
      'view_details': 'عرض التفاصيل',
      'order_report': 'تقرير الطلب',
      'details': 'التفاصيل',
      'transaction_id': 'رقم العملية',
      'payment_method': 'طريقة الدفع',
      'phone_number': 'رقم الهاتف',
      'order_date': 'Order Date',
      'total_amount': 'المبلغ الإجمالي',
      'status': 'الحالة',
      'order_number': 'رقم الطلب',
      'app_updates': 'تحديثات التطبيق',
      'manage_app_updates': 'إدارة تحديثات النظام',
      'version_name': 'رقم الإصدار',
      'download_url': 'رابط التحميل',
      'release_notes': 'ملاحظات الإصدار',
      'is_mandatory_label': 'تحديث إجباري',
      'add_update': 'إضافة تحديث جديد',
      'update_success': 'تم إضافة التحديث بنجاح',
      'mandatory': 'إجباري',
      'optional': 'اختياري',
      'show_all': 'عرض الكل',
    },
    'en': {
      'settings': 'Settings',
      'profile': 'Profile',
      'name': 'Name',
      'change_photo': 'Change Photo',
      'theme': 'Appearance',
      'display_mode': 'Display Mode',
      'light': 'Light',
      'dark': 'Dark',
      'system': 'System',
      'notifications': 'Notifications',
      'enable_notifications': 'Enable Notifications',
      'notifications_desc': 'Receive notifications for lessons and exams',
      'downloads': 'Downloads',
      'auto_download': 'Auto Download',
      'auto_download_desc': 'Automatically download lessons when connected to Wi-Fi',
      'wifi_only': 'Wi-Fi Only',
      'wifi_only_desc': 'Save data by downloading only over Wi-Fi',
      'video_quality': 'Video Quality',
      'clear_downloads': 'Clear Downloads',
      'clear_downloads_desc': 'Delete all downloaded lessons to save space',
      'about': 'About',
      'version': 'Version',
      'privacy_policy': 'Privacy Policy',
      'terms_conditions': 'Terms of Service',
      'language': 'Language',
      'app_language': 'App Language',
      'logout': 'Log Out',
      'logout_confirm_title': 'Log Out',
      'logout_confirm_desc': 'Are you sure you want to log out?',
      'cancel': 'Cancel',
      'save': 'Save',
      'edit_name': 'Edit Name',
      'enter_full_name': 'Enter full name',
      'choose_photo': 'Choose Photo',
      'camera': 'Camera',
      'gallery': 'Gallery',
      'video_quality_high': 'High',
      'video_quality_medium': 'Medium',
      'video_quality_low': 'Low',
      'clear_downloads_confirm_title': 'Clear Downloads',
      'clear_downloads_confirm_desc': 'Are you sure you want to clear all downloads?',
      'clear': 'Clear',
      'clearing': 'Clearing downloads...',
      'clear_success': 'All downloads cleared successfully',
      'error_loading': 'Error loading data',
      'changes_saved': 'Changes saved',
      'error_saving': 'Error saving changes',
      'error_image_pick': 'Error picking image',
      'error_image_upload': 'Error uploading image',
      'error_logout': 'Error logging out',
      'contact_support': 'Contact Support',
      'support_desc': 'Technical support and help',
      'delete_account': 'Delete Account',
      'delete_account_desc': 'Permanently delete your account and data',
      'delete_confirm_title': 'Delete Account',
      'delete_confirm_desc': 'Are you sure you want to delete your account? This action cannot be undone.',
      'delete': 'Delete',
      'support_dialog_title': 'Technical Support',
      'support_dialog_desc': 'You can contact us through:',
      'email_us': 'Email Us',
      'whatsapp_us': 'WhatsApp Us',
      'home': 'Home',
      'explore': 'Explore',
      'my_courses': 'My Courses',
      'welcome': 'Welcome, Guest',
      'guest': 'Guest',
      'searching': 'Search your next lesson...',
      'categories': 'Categories',
      'all': 'All',
      'top_teachers': 'Top Teachers',
      'continue_watching': 'Continue Watching',
      'explore_more': 'Explore More',
      'search_courses': 'Search Courses',
      'search_hint': 'Search by course or teacher...',
      'filter': 'Filter',
      'filter_by_category': 'Filter by Category',
      'my_downloads': 'My Downloads',
      'edit_profile': 'Edit Profile',
      'statistics': 'Statistics',
      'joined': 'Joined',
      'completed_courses': 'Completed Courses',
      'hours_spent': 'Study Hours',
      'no_courses_found': 'No courses found',
      'try_different_search': 'Try searching with different keywords',
      'featured_courses': 'Featured Courses',
      'no_featured_courses_message': 'No featured courses found at the moment.',
      'welcome_with_name': 'Welcome,',
      'lessons': 'lessons',
      'ready_to_learn': 'Ready to learn?',
      'search_course_hint': 'Search for a course...',
      'continue_learning': 'Continue Learning',
      'completed': 'Completed',
      'featured_course_badge': 'Featured',
      'most_popular': 'Most Popular',
      'teacher': 'Teacher',
      'explore_courses': 'Explore Courses',
      'no_courses_in_category': 'No courses in this category',
      'no_categories_found': 'No categories found',
      'loading': 'Loading...',
      'current_courses': 'Current Courses',
      'completed_status': 'Completed',
      'reviews': 'reviews',
      'enrolled': 'Enrolled',
      'no_current_courses': 'No current courses',
      'no_completed_courses': 'No completed courses yet',
      'unenroll_confirm': 'Are you sure you want to unenroll?',
      'unenroll_success': 'Course removed from your list',
      'unenroll_error': 'Error during unenrollment',
      'course_removed': 'Course removed successfully',
      'no_current_courses_desc': 'Start exploring courses and enroll in your interests!',
      'no_completed_courses_desc': 'Once you finish a course, it will appear here in the completed list.',
      'current': 'Current',
      'admin_dashboard': 'Admin Dashboard',
      'teacher_dashboard': 'Teacher Dashboard',
      'account_upgrades': 'Account Upgrades',
      'certificates': 'Certificates',
      'learning_hours': 'Learning Hours',
      'orders': 'My Orders',
      'dashboard': 'Dashboard',
      'user': 'User',
      'completed_courses_count_label': 'Completed Course(s)',
      'no_orders_yet': 'No previous orders',
      'no_orders_desc': 'You haven\'t purchased any courses yet. All your bills will appear here.',
      'study_continue': 'Keep studying!',
      'courses_not_completed_desc': 'You haven\'t completed any course fully yet. Keep studying!',
      'enrolled_courses_desc': 'Start your educational journey today and explore our available courses.',
      'no_courses_yet': 'You haven\'t purchased any course yet',
      'course_description': 'Course Description',
      'curriculum_tab': 'Curriculum',
      'reviews_tab': 'Reviews',
      'reviews_label': 'Review',
      'progress_label': 'Progress',
      'offline_badge_label': 'Downloaded',
      'unenroll_button_label': 'Remove from list',
      'course_unavailable_label': 'Currently unavailable',
      'no_active_courses': 'No active courses',
      'start_learning_message': 'Start by adding courses from the home screen',
      'keep_learning_message': 'Keep learning to complete your courses!',
      'confirm_delete_title': 'Confirm Delete',
      'confirm_delete_message': 'Do you want to remove this course from your list?',
      'error_label': 'Error',
      'buy_now': 'Buy Now',
      'enrolled_already': 'You are enrolled in this course',
      'pending_request': 'Your request is pending',
      'download_course': 'Download Course',
      'get_certificate': 'Get Certificate',
      'lesson': 'Lesson',
      'exam': 'Exam',
      'free': 'Free',
      'certificate_ready': 'Certificate is ready!',
      'premium_course': 'Premium Course',
      'no_instructor_profile': 'No instructor profile available',
      'instructor_title': 'Instructor',
      'lessons_count_label': 'Lessons',
      'reviews_count_label': 'Reviews',
      'students_count_label': 'Students',
      'duration_label': 'Hours',
      'no_reviews_yet': 'No reviews yet',
      'add_review': 'Add your review',
      'your_comment_here': 'Write your comment here...',
      'publish': 'Publish',
      'adding_review': 'Adding review...',
      'review_added_success': 'Your review has been added successfully',
      'no_lessons_yet': 'No lessons yet',
      'course_content_working': 'Content is being added to this course soon.',
      'other_lessons': 'Other Lessons',
      'course_content': 'Course Content',
      'must_complete_previous': 'You must complete the previous lesson first',
      'description_tab': 'Description',
      'attachments_tab': 'Attachments',
      'interactive_tab': 'Interactive',
      'exams_tab': 'Exams',
      'notes_tab': 'Notes',
      'questions_tab': 'Questions',
      'lesson_prefix': 'Lesson',
      'starting_download': 'Preparing file...',
      'download_success_encrypted': 'File prepared successfully',
      'download_error': 'Download error',
      'delete_note': 'Delete Note',
      'delete_note_confirm': 'Are you sure you want to delete this note?',
      'note_deleted_success': 'Note deleted successfully',
      'edit_note': 'Edit Note',
      'no_video_available': 'No video available for this lesson',
      'no_interactive_content': 'No interactive content for this lesson',
      'flashcards_tab': 'Flashcards',
      'generate_flashcards': 'Generate AI Flashcards',
      'review_flashcards': 'Review Flashcards',
      'flashcards_desc':
          'Smart flashcards based on lesson content to help you memorize and review using spaced repetition.',
      'generating_flashcards': 'Generating flashcards using AI...',
      'flashcards_generated_success':
          'Flashcards generated successfully! You can now start reviewing.',
      'recent_exam_attempts': 'Recent Student Attempts',
      'no_recent_attempts': 'No recent attempts',
      'must_subscribe': 'You must subscribe to the course to watch this lesson',
      'no_exam_at_all': 'No exam for this lesson. Moving to next...',
      'must_take_exam': 'You must pass the exam for this lesson first',
      'start_exam': 'Start Exam',
      'discussions': 'Discussions',
      'discussions_coming_soon': 'Feature available in a future update',
      'ai_assistant': 'AI Assistant',
      'ai_assistant_coming_soon':
          'AI features will be available in a future update',
      'ai_features_notice':
          'We are working on integrating AI technologies to enhance your learning experience.',
      'view_details': 'View Details',
      'order_report': 'Order Report',
      'details': 'Details',
      'transaction_id': 'Transaction ID',
      'payment_method': 'Payment Method',
      'phone_number': 'Phone Number',
      'order_date': 'Order Date',
      'total_amount': 'Total Amount',
      'status': 'Status',
      'order_number': 'Order Number',
      'app_updates': 'App Updates',
      'manage_app_updates': 'Manage App Updates',
      'version_name': 'Version Name',
      'download_url': 'Download URL',
      'release_notes': 'Release Notes',
      'is_mandatory_label': 'Mandatory Update',
      'add_update': 'Add New Update',
      'update_success': 'Update added successfully',
      'mandatory': 'Mandatory',
      'optional': 'Optional',
      'show_all': 'Show All',
    },
  };

  static String get(String key, String lang) {
    return _localizedValues[lang]?[key] ?? _localizedValues['ar']?[key] ?? key;
  }
}
